export const CEFR_LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"] as const;
export type CefrLevelCode = (typeof CEFR_LEVELS)[number];

export const GRAMMAR_CATEGORIES = [
  "SENTENCE_STRUCTURE",
  "CASES",
  "VERBS",
  "TENSES",
  "ARTICLES",
  "ADJECTIVES",
  "PREPOSITIONS",
  "PRONOUNS",
  "CONJUNCTIONS",
  "RELATIVE_CLAUSES",
  "NEGATION",
  "COMPARISON",
  "PASSIVE",
  "SUBJUNCTIVE",
  "INFINITIVE_CONSTRUCTIONS",
  "NOUNS",
  "ADVERBS_PARTICLES",
  "WORD_FORMATION",
] as const;

export type GrammarCategoryCode = (typeof GRAMMAR_CATEGORIES)[number];
export type GrammarRelationCode = "RELATED" | "CONTRASTS_WITH" | "EXTENDS";

export type GrammarCurriculumConcept = {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  category: GrammarCategoryCode;
  secondaryCategories?: GrammarCategoryCode[];
  introducedAt: CefrLevelCode;
  expectedBy?: CefrLevelCode;
  reinforcedAt?: CefrLevelCode[];
  parentId?: string;
  order: number;
  explanation?: string;
  rules?: string[];
  exceptions?: string[];
  examples?: string[];
  prerequisites?: string[];
  related?: Array<{ targetId: string; type?: GrammarRelationCode }>;
};

export const cefrRank: Record<CefrLevelCode, number> = {
  A1: 1,
  A2: 2,
  B1: 3,
  B2: 4,
  C1: 5,
  C2: 6,
};

export const grammarCurriculum: GrammarCurriculumConcept[] = [
  {
    id: "de.sentence.main-clause-v2",
    slug: "main-clause-v2",
    title: "Main-clause V2 word order",
    shortDescription: "Place the finite verb in the second syntactic position of a German main clause.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "A1",
    expectedBy: "A1",
    reinforcedAt: ["A2", "B1"],
    order: 10,
    rules: ["The finite verb occupies position two.", "Another constituent may occupy position one."],
    examples: ["Ich lerne heute Deutsch.", "Heute lerne ich Deutsch."],
  },
  {
    id: "de.sentence.yes-no-questions",
    slug: "yes-no-questions",
    title: "Yes/no questions",
    shortDescription: "Form yes/no questions with the finite verb in first position.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "A1",
    expectedBy: "A1",
    order: 20,
    prerequisites: ["de.sentence.main-clause-v2"],
    examples: ["Kommst du morgen?", "Hast du Zeit?"],
  },
  {
    id: "de.sentence.w-questions",
    slug: "w-questions",
    title: "W-questions",
    shortDescription: "Form information questions with an interrogative element followed by the finite verb.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "A1",
    expectedBy: "A1",
    order: 30,
    prerequisites: ["de.sentence.main-clause-v2"],
    examples: ["Wo wohnst du?", "Warum lernst du Deutsch?"],
  },
  {
    id: "de.sentence.time-manner-place",
    slug: "time-manner-place",
    title: "Time–manner–place ordering",
    shortDescription: "Use the common neutral ordering of adverbial information in German clauses.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "A2",
    expectedBy: "B1",
    reinforcedAt: ["B1", "B2"],
    order: 40,
    prerequisites: ["de.sentence.main-clause-v2"],
    examples: ["Ich fahre morgen mit dem Zug nach Berlin."],
  },
  {
    id: "de.sentence.indirect-questions",
    slug: "indirect-questions",
    title: "Indirect questions",
    shortDescription: "Embed questions with ob or an interrogative word and subordinate-clause word order.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 50,
    prerequisites: ["de.conjunction.subordinate-verb-final", "de.sentence.w-questions"],
    examples: ["Ich weiß nicht, ob er kommt.", "Kannst du mir sagen, wo sie wohnt?"],
  },
  {
    id: "de.sentence.complex-clause-order",
    slug: "complex-clause-order",
    title: "Complex clause ordering",
    shortDescription: "Combine multiple main and subordinate clauses while preserving verb placement and clear information flow.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 60,
    prerequisites: ["de.conjunction.subordinate-verb-final", "de.conjunction.complex-connectors"],
  },

  {
    id: "de.case.nominative",
    slug: "nominative-case",
    title: "Nominative case",
    shortDescription: "Use nominative forms for subjects and predicate nouns.",
    category: "CASES",
    introducedAt: "A1",
    expectedBy: "A1",
    order: 100,
    examples: ["Der Mann arbeitet.", "Das ist ein Problem."],
  },
  {
    id: "de.case.accusative",
    slug: "accusative-case",
    title: "Accusative case",
    shortDescription: "Use accusative forms for many direct objects and after accusative-governing prepositions.",
    category: "CASES",
    introducedAt: "A1",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 110,
    prerequisites: ["de.case.nominative", "de.article.definite"],
    examples: ["Ich sehe den Mann.", "Sie kauft einen Kaffee."],
  },
  {
    id: "de.case.dative",
    slug: "dative-case",
    title: "Dative case",
    shortDescription: "Use dative forms for many indirect objects, verbs and prepositions that govern dative.",
    category: "CASES",
    introducedAt: "A2",
    expectedBy: "A2",
    reinforcedAt: ["B1", "B2"],
    order: 120,
    prerequisites: ["de.case.accusative", "de.article.definite"],
    examples: ["Ich helfe dem Mann.", "Sie spricht mit ihrer Freundin."],
  },
  {
    id: "de.case.genitive",
    slug: "genitive-case",
    title: "Genitive case",
    shortDescription: "Use genitive for possession and with selected formal prepositions and constructions.",
    category: "CASES",
    introducedAt: "B1",
    expectedBy: "B2",
    reinforcedAt: ["B2"],
    order: 130,
    prerequisites: ["de.case.dative"],
    examples: ["Wegen des Wetters bleiben wir zu Hause.", "Das ist das Auto meines Bruders."],
  },

  {
    id: "de.article.definite",
    slug: "definite-articles",
    title: "Definite articles",
    shortDescription: "Use der, die, das and their case forms with definite noun phrases.",
    category: "ARTICLES",
    introducedAt: "A1",
    expectedBy: "A1",
    reinforcedAt: ["A2"],
    order: 200,
    examples: ["der Tisch", "die Stadt", "das Buch"],
  },
  {
    id: "de.article.indefinite",
    slug: "indefinite-articles",
    title: "Indefinite articles",
    shortDescription: "Use ein/eine and their case forms with indefinite noun phrases.",
    category: "ARTICLES",
    introducedAt: "A1",
    expectedBy: "A1",
    reinforcedAt: ["A2"],
    order: 210,
    prerequisites: ["de.article.definite"],
    examples: ["ein Tisch", "eine Stadt", "ein Buch"],
  },
  {
    id: "de.article.possessive-determiners",
    slug: "possessive-determiners",
    title: "Possessive determiners",
    shortDescription: "Use mein, dein, sein, ihr and related forms with case and gender agreement.",
    category: "ARTICLES",
    introducedAt: "A1",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 220,
    prerequisites: ["de.article.indefinite"],
    examples: ["mein Bruder", "mit meiner Freundin"],
  },

  {
    id: "de.pronoun.personal",
    slug: "personal-pronouns",
    title: "Personal pronouns",
    shortDescription: "Use German subject pronouns and distinguish person, number and formal Sie.",
    category: "PRONOUNS",
    introducedAt: "A1",
    expectedBy: "A1",
    order: 300,
    examples: ["ich", "du", "er", "sie", "es", "wir", "ihr", "Sie"],
  },
  {
    id: "de.pronoun.accusative-dative",
    slug: "accusative-dative-pronouns",
    title: "Accusative and dative pronouns",
    shortDescription: "Choose object-pronoun forms such as mich/mir and ihn/ihm according to case.",
    category: "PRONOUNS",
    introducedAt: "A2",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 310,
    prerequisites: ["de.pronoun.personal", "de.case.accusative", "de.case.dative"],
    examples: ["Er sieht mich.", "Er hilft mir."],
  },
  {
    id: "de.pronoun.reflexive",
    slug: "reflexive-pronouns",
    title: "Reflexive pronouns",
    shortDescription: "Use reflexive pronouns with reflexive verbs and reflexive meanings.",
    category: "PRONOUNS",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 320,
    prerequisites: ["de.pronoun.accusative-dative"],
    examples: ["Ich erinnere mich.", "Sie wäscht sich die Hände."],
  },
  {
    id: "de.pronoun.da-wo-compounds",
    slug: "da-wo-compounds",
    title: "Da-/wo- compounds",
    shortDescription: "Use daran, damit, worauf and related forms for things and clauses with prepositions.",
    category: "PRONOUNS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 330,
    prerequisites: ["de.preposition.prepositional-verbs"],
    examples: ["Ich denke daran.", "Worauf wartest du?"],
  },

  {
    id: "de.verb.present-regular",
    slug: "present-tense",
    title: "Present tense",
    shortDescription: "Conjugate regular and common irregular verbs in Präsens.",
    category: "VERBS",
    introducedAt: "A1",
    expectedBy: "A1",
    reinforcedAt: ["A2"],
    order: 400,
    examples: ["ich lerne", "du arbeitest", "er fährt"],
  },
  {
    id: "de.verb.sein-haben",
    slug: "sein-haben-present",
    title: "sein and haben",
    shortDescription: "Use the highly irregular present-tense forms of sein and haben.",
    category: "VERBS",
    introducedAt: "A1",
    expectedBy: "A1",
    order: 410,
    examples: ["Ich bin müde.", "Wir haben Zeit."],
  },
  {
    id: "de.verb.modal",
    slug: "modal-verbs",
    title: "Modal verbs",
    shortDescription: "Use modal verbs with a finite modal and infinitive at the end of the clause.",
    category: "VERBS",
    introducedAt: "A1",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 420,
    prerequisites: ["de.verb.present-regular", "de.sentence.main-clause-v2"],
    examples: ["Ich muss heute arbeiten.", "Wir können morgen kommen."],
  },
  {
    id: "de.verb.separable",
    slug: "separable-verbs",
    title: "Separable verbs",
    shortDescription: "Separate verb prefixes in finite main clauses and keep them joined in appropriate non-finite forms.",
    category: "VERBS",
    introducedAt: "A1",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 430,
    prerequisites: ["de.verb.present-regular", "de.sentence.main-clause-v2"],
    examples: ["Ich stehe um sieben Uhr auf.", "Ich möchte früh aufstehen."],
  },
  {
    id: "de.verb.imperative",
    slug: "imperative",
    title: "Imperative",
    shortDescription: "Form informal and formal commands and requests.",
    category: "VERBS",
    introducedAt: "A1",
    expectedBy: "A2",
    order: 440,
    prerequisites: ["de.verb.present-regular"],
    examples: ["Komm bitte!", "Kommen Sie bitte herein!"],
  },
  {
    id: "de.verb.reflexive",
    slug: "reflexive-verbs",
    title: "Reflexive verbs",
    shortDescription: "Use common reflexive verbs with the appropriate reflexive pronoun and case.",
    category: "VERBS",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 450,
    prerequisites: ["de.pronoun.reflexive"],
    examples: ["Ich interessiere mich für Musik.", "Sie erinnert sich an den Termin."],
  },
  {
    id: "de.verb.valency-case",
    slug: "verb-case-government",
    title: "Verb case government",
    shortDescription: "Learn verbs that require dative, accusative or particular argument structures.",
    category: "VERBS",
    introducedAt: "A2",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 460,
    prerequisites: ["de.case.accusative", "de.case.dative"],
    examples: ["jemandem helfen", "jemandem danken", "jemanden fragen"],
  },

  {
    id: "de.tense.perfekt",
    slug: "perfekt",
    title: "Perfekt",
    shortDescription: "Form the conversational past with haben/sein and the past participle.",
    category: "TENSES",
    introducedAt: "A2",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 500,
    prerequisites: ["de.verb.present-regular", "de.verb.sein-haben"],
    examples: ["Ich habe gearbeitet.", "Sie ist nach Hause gegangen."],
  },
  {
    id: "de.tense.praeteritum-core",
    slug: "praeteritum-core-verbs",
    title: "Präteritum of core verbs",
    shortDescription: "Use common simple-past forms, especially sein, haben and modal verbs.",
    category: "TENSES",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 510,
    prerequisites: ["de.verb.sein-haben", "de.verb.modal"],
    examples: ["Ich war müde.", "Wir hatten keine Zeit.", "Er musste gehen."],
  },
  {
    id: "de.tense.praeteritum-narrative",
    slug: "praeteritum-narrative",
    title: "Narrative Präteritum",
    shortDescription: "Use a wider range of simple-past verb forms in written narrative and formal contexts.",
    category: "TENSES",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 520,
    prerequisites: ["de.tense.praeteritum-core"],
    examples: ["Er öffnete die Tür und ging hinein."],
  },
  {
    id: "de.tense.plusquamperfekt",
    slug: "plusquamperfekt",
    title: "Plusquamperfekt",
    shortDescription: "Express an event completed before another past event.",
    category: "TENSES",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 530,
    prerequisites: ["de.tense.perfekt", "de.tense.praeteritum-core"],
    examples: ["Nachdem ich gegessen hatte, ging ich spazieren."],
  },
  {
    id: "de.tense.future",
    slug: "future-werden",
    title: "Future with werden",
    shortDescription: "Use werden + infinitive for future reference and selected modal meanings.",
    category: "TENSES",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 540,
    prerequisites: ["de.verb.present-regular"],
    examples: ["Ich werde morgen anrufen."],
  },

  {
    id: "de.negation.nicht-kein",
    slug: "nicht-and-kein",
    title: "Negation with nicht and kein",
    shortDescription: "Choose nicht or kein and place negation appropriately in simple clauses.",
    category: "NEGATION",
    introducedAt: "A1",
    expectedBy: "A1",
    reinforcedAt: ["A2", "B1"],
    order: 600,
    prerequisites: ["de.article.indefinite"],
    examples: ["Ich komme heute nicht.", "Ich habe kein Auto."],
  },
  {
    id: "de.negation.position",
    slug: "negation-position",
    title: "Advanced negation placement",
    shortDescription: "Place nicht according to the constituent or scope being negated.",
    category: "NEGATION",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 610,
    prerequisites: ["de.negation.nicht-kein", "de.sentence.main-clause-v2"],
  },

  {
    id: "de.preposition.accusative",
    slug: "accusative-prepositions",
    title: "Accusative prepositions",
    shortDescription: "Use common prepositions that consistently govern the accusative case.",
    category: "PREPOSITIONS",
    introducedAt: "A1",
    expectedBy: "A2",
    order: 700,
    prerequisites: ["de.case.accusative"],
    examples: ["für dich", "ohne einen Termin", "durch den Park"],
  },
  {
    id: "de.preposition.dative",
    slug: "dative-prepositions",
    title: "Dative prepositions",
    shortDescription: "Use common prepositions that consistently govern the dative case.",
    category: "PREPOSITIONS",
    introducedAt: "A2",
    expectedBy: "A2",
    order: 710,
    prerequisites: ["de.case.dative"],
    examples: ["mit dem Zug", "bei meiner Freundin", "nach der Arbeit"],
  },
  {
    id: "de.preposition.two-way",
    slug: "two-way-preposition-usage",
    title: "Two-way preposition usage",
    shortDescription: "Use an, auf, hinter, in, neben, über, unter, vor and zwischen with accusative for a destination/change of spatial relationship and dative for location within an existing spatial relationship.",
    category: "PREPOSITIONS",
    secondaryCategories: ["CASES"],
    introducedAt: "A2",
    expectedBy: "B1",
    order: 720,
    prerequisites: ["de.preposition.accusative", "de.preposition.dative"],
  },
  {
    id: "de.preposition.prepositional-verbs",
    slug: "prepositional-verbs",
    title: "Prepositional verbs",
    shortDescription: "Learn verb + preposition + case combinations as lexical patterns.",
    category: "PREPOSITIONS",
    introducedAt: "A2",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 730,
    prerequisites: ["de.case.accusative", "de.case.dative"],
    examples: ["warten auf + Akk.", "teilnehmen an + Dat.", "abhängen von + Dat."],
  },
  {
    id: "de.preposition.genitive",
    slug: "genitive-prepositions",
    title: "Genitive prepositions",
    shortDescription: "Use selected formal prepositions with genitive, while recognizing common register variation.",
    category: "PREPOSITIONS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 740,
    prerequisites: ["de.case.genitive"],
    examples: ["wegen des Wetters", "trotz des Problems", "während des Urlaubs"],
  },

  {
    id: "de.adjective.predicative",
    slug: "predicative-adjectives",
    title: "Predicative adjectives",
    shortDescription: "Use uninflected adjectives after verbs such as sein, werden and bleiben.",
    category: "ADJECTIVES",
    introducedAt: "A1",
    expectedBy: "A1",
    order: 800,
    examples: ["Das Buch ist interessant."],
  },
  {
    id: "de.adjective.endings-basic",
    slug: "adjective-endings-basic",
    title: "Basic adjective endings",
    shortDescription: "Use common adjective endings in frequent nominative and accusative noun phrases.",
    category: "ADJECTIVES",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 810,
    prerequisites: ["de.article.definite", "de.article.indefinite", "de.case.accusative"],
    examples: ["ein gutes Buch", "den neuen Film"],
  },
  {
    id: "de.adjective.declension",
    slug: "adjective-declension",
    title: "Adjective declension",
    shortDescription: "Choose weak, mixed and strong adjective endings across gender, number and case.",
    category: "ADJECTIVES",
    introducedAt: "B1",
    expectedBy: "B2",
    reinforcedAt: ["B2"],
    order: 820,
    prerequisites: ["de.adjective.endings-basic", "de.case.dative", "de.case.genitive"],
    examples: ["mit einem guten Freund", "frisches Brot", "die neuen Regeln", "ein größerer Teil", "der größte Teil"],
  },
  {
    id: "de.comparison.comparative-superlative",
    slug: "comparative-superlative",
    title: "Comparative and superlative",
    shortDescription: "Form and use comparative and superlative adjectives and adverbs.",
    category: "COMPARISON",
    introducedAt: "A2",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 850,
    examples: ["schneller", "am schnellsten", "größer als"],
  },

  {
    id: "de.conjunction.coordinating",
    slug: "coordinating-conjunctions",
    title: "Coordinating conjunctions",
    shortDescription: "Connect clauses with und, aber, oder, denn and sondern without changing main-clause verb position.",
    category: "CONJUNCTIONS",
    introducedAt: "A1",
    expectedBy: "A2",
    order: 900,
    prerequisites: ["de.sentence.main-clause-v2"],
    examples: ["Ich komme, aber ich bleibe nicht lange."],
  },
  {
    id: "de.conjunction.subordinate-verb-final",
    slug: "subordinate-clause-word-order",
    title: "Subordinate-clause verb-final order",
    shortDescription: "Move the finite verb to the end of clauses introduced by subordinating conjunctions.",
    category: "CONJUNCTIONS",
    introducedAt: "A2",
    expectedBy: "B1",
    reinforcedAt: ["B1", "B2"],
    order: 910,
    prerequisites: ["de.sentence.main-clause-v2"],
    examples: ["Ich bleibe zu Hause, weil ich krank bin.", "Ich weiß, dass er heute kommt."],
  },
  {
    id: "de.conjunction.temporal",
    slug: "temporal-conjunctions",
    title: "Temporal conjunctions",
    shortDescription: "Express time relations with als, wenn, bevor, nachdem, während, seitdem and similar connectors.",
    category: "CONJUNCTIONS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 920,
    prerequisites: ["de.conjunction.subordinate-verb-final"],
    examples: [
      "Als ich ein Kind war, wohnte ich in Köln.",
      "Wenn ich Zeit habe, lese ich.",
      "Bevor du gehst, ruf mich an.",
      "Nachdem ich gegessen hatte, ging ich spazieren.",
      "Während ich arbeite, höre ich Musik.",
      "Seitdem er umgezogen ist, sehen wir uns seltener.",
      "Warte, bis ich fertig bin.",
    ],
  },
  {
    id: "de.conjunction.concession",
    slug: "concessive-connections",
    title: "Concession with obwohl and trotzdem",
    shortDescription: "Contrast facts using subordinate and main-clause connective patterns.",
    category: "CONJUNCTIONS",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 930,
    prerequisites: ["de.conjunction.subordinate-verb-final"],
    examples: ["Obwohl es regnet, gehen wir spazieren.", "Es regnet. Trotzdem gehen wir spazieren."],
  },
  {
    id: "de.conjunction.complex-connectors",
    slug: "complex-connectors",
    title: "Complex connectors",
    shortDescription: "Use paired and formal connectors to structure contrast, cause, consequence and alternatives.",
    category: "CONJUNCTIONS",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 940,
    prerequisites: ["de.conjunction.coordinating", "de.conjunction.subordinate-verb-final"],
    examples: ["nicht nur … sondern auch", "einerseits … andererseits", "sowohl … als auch", "entweder … oder", "weder … noch", "zwar … aber", "je … desto/umso"],
  },

  {
    id: "de.infinitive.zu",
    slug: "infinitive-with-zu",
    title: "Infinitive clauses with zu",
    shortDescription: "Use zu + infinitive with verbs, adjectives and noun expressions that license an infinitive clause.",
    category: "INFINITIVE_CONSTRUCTIONS",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 1000,
    prerequisites: ["de.verb.present-regular"],
    examples: ["Ich versuche, früher zu schlafen.", "Es ist wichtig, pünktlich zu sein."],
  },
  {
    id: "de.infinitive.um-ohne-statt",
    slug: "um-ohne-statt-zu",
    title: "um/ohne/statt … zu",
    shortDescription: "Express purpose or accompanying circumstances with infinitive constructions.",
    category: "INFINITIVE_CONSTRUCTIONS",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 1010,
    prerequisites: ["de.infinitive.zu"],
    examples: [
      "Ich lerne viel, um die Prüfung zu bestehen.",
      "Er ging, ohne sich zu verabschieden.",
      "Statt zu arbeiten, sah er fern.",
    ],
  },
  {
    id: "de.infinitive.advanced",
    slug: "advanced-infinitive-constructions",
    title: "Advanced infinitive constructions",
    shortDescription: "Use expanded infinitive groups and select between infinitive and finite subordinate clauses.",
    category: "INFINITIVE_CONSTRUCTIONS",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1020,
    prerequisites: ["de.infinitive.um-ohne-statt", "de.conjunction.subordinate-verb-final"],
  },

  {
    id: "de.relative.basic",
    slug: "relative-clauses",
    title: "Relative clauses",
    shortDescription: "Form relative clauses with case-marked relative pronouns and verb-final order.",
    category: "RELATIVE_CLAUSES",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 1100,
    prerequisites: ["de.case.accusative", "de.case.dative", "de.conjunction.subordinate-verb-final"],
    examples: ["Das ist der Mann, der hier arbeitet.", "Das ist die Frau, die ich kenne."],
  },
  {
    id: "de.relative.prepositions",
    slug: "relative-pronouns-with-prepositions",
    parentId: "de.relative.basic",
    title: "Relative pronouns with prepositions",
    shortDescription: "Choose relative-pronoun case after prepositions inside relative clauses.",
    category: "RELATIVE_CLAUSES",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1110,
    prerequisites: ["de.relative.basic", "de.preposition.prepositional-verbs"],
    examples: ["Das ist das Thema, über das wir gesprochen haben."],
  },
  {
    id: "de.relative.was-wo",
    slug: "relative-was-wo",
    parentId: "de.relative.basic",
    title: "Relative clauses with was and wo",
    shortDescription: "Use was and wo in common relative constructions after pronouns, clauses and place expressions.",
    category: "RELATIVE_CLAUSES",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1120,
    prerequisites: ["de.relative.basic"],
  },

  {
    id: "de.passive.present",
    slug: "passive-present",
    title: "Process passive in the present",
    shortDescription: "Form Vorgangspassiv with werden + past participle.",
    category: "PASSIVE",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 1200,
    prerequisites: ["de.verb.present-regular", "de.tense.perfekt"],
    examples: ["Das Haus wird gebaut."],
  },
  {
    id: "de.passive.past",
    slug: "passive-past",
    parentId: "de.passive.present",
    title: "Passive in past tenses",
    shortDescription: "Use passive constructions in Präteritum and Perfekt.",
    category: "PASSIVE",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 1210,
    prerequisites: ["de.passive.present", "de.tense.praeteritum-core"],
    examples: ["Das Haus wurde gebaut.", "Das Haus ist gebaut worden."],
  },
  {
    id: "de.passive.alternatives",
    slug: "passive-alternatives",
    parentId: "de.passive.present",
    title: "Alternatives to the passive",
    shortDescription: "Use man, sich lassen and sein + zu constructions where German prefers alternatives to werden-passive.",
    category: "PASSIVE",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1220,
    prerequisites: ["de.passive.present", "de.infinitive.zu"],
  },

  {
    id: "de.subjunctive.konjunktiv-ii-polite",
    slug: "konjunktiv-ii-polite",
    title: "Konjunktiv II for polite requests",
    shortDescription: "Use würde, hätte, wäre and modal subjunctive forms for polite and softened requests.",
    category: "SUBJUNCTIVE",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 1300,
    prerequisites: ["de.verb.modal", "de.verb.sein-haben"],
    examples: ["Könnten Sie mir helfen?", "Ich hätte gern einen Kaffee."],
  },
  {
    id: "de.subjunctive.konjunktiv-ii-hypothetical",
    slug: "konjunktiv-ii-hypothetical",
    parentId: "de.subjunctive.konjunktiv-ii-polite",
    title: "Konjunktiv II for hypothetical situations",
    shortDescription: "Express unreal, hypothetical and wished-for situations with Konjunktiv II.",
    category: "SUBJUNCTIVE",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 1310,
    prerequisites: ["de.subjunctive.konjunktiv-ii-polite", "de.conjunction.subordinate-verb-final"],
    examples: ["Wenn ich mehr Zeit hätte, würde ich mehr lesen."],
  },
  {
    id: "de.subjunctive.konjunktiv-ii-past",
    slug: "konjunktiv-ii-past",
    parentId: "de.subjunctive.konjunktiv-ii-hypothetical",
    title: "Past Konjunktiv II",
    shortDescription: "Express unreal past conditions, regrets and counterfactual outcomes.",
    category: "SUBJUNCTIVE",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1320,
    prerequisites: ["de.subjunctive.konjunktiv-ii-hypothetical", "de.tense.perfekt"],
    examples: ["Wenn ich das gewusst hätte, wäre ich früher gekommen."],
  },
  {
    id: "de.subjunctive.konjunktiv-i-reporting",
    slug: "konjunktiv-i-reported-speech",
    title: "Konjunktiv I in reported speech",
    shortDescription: "Recognize and use Konjunktiv I for indirect reporting, especially in formal written German.",
    category: "SUBJUNCTIVE",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1330,
    prerequisites: ["de.verb.present-regular", "de.sentence.complex-clause-order"],
    examples: ["Er sagte, er habe keine Zeit."],
  },

  {
    id: "de.noun.plural",
    slug: "noun-plurals",
    title: "Noun plural patterns",
    shortDescription: "Recognize and produce common German plural patterns as lexical information.",
    category: "NOUNS",
    introducedAt: "A1",
    expectedBy: "A2",
    order: 1400,
    examples: ["der Tisch → die Tische", "die Stadt → die Städte"],
  },
  {
    id: "de.noun.weak-nouns",
    slug: "weak-nouns",
    title: "Weak masculine nouns",
    shortDescription: "Use n-declension endings for common weak masculine nouns outside nominative singular.",
    category: "NOUNS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 1410,
    prerequisites: ["de.case.accusative", "de.case.dative", "de.case.genitive"],
    examples: ["der Student → mit dem Studenten"],
  },
  {
    id: "de.noun.nominalization",
    slug: "nominalization",
    title: "Nominalization",
    shortDescription: "Recognize and form common nominalized verbs and adjectives in formal and abstract language.",
    category: "NOUNS",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1420,
    prerequisites: ["de.adjective.declension"],
    examples: ["das Lesen", "die Arbeitslosen"],
  },

  {
    id: "de.sentence.verb-bracket",
    slug: "verb-bracket-satzklammer",
    title: "Verb bracket (Satzklammer)",
    shortDescription: "Build German clauses with a finite verb in the left bracket and separable, infinitive or participial material in the right bracket.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "A1",
    expectedBy: "A2",
    reinforcedAt: ["B1", "B2"],
    order: 11,
    prerequisites: ["de.sentence.main-clause-v2"],
    examples: ["Ich stehe um sieben Uhr auf.", "Ich muss heute lange arbeiten.", "Ich habe gestern lange gearbeitet."],
  },
  {
    id: "de.sentence.mittelfeld-basics",
    slug: "mittelfeld-word-order-basics",
    title: "Basic word order in the Mittelfeld",
    shortDescription: "Order pronouns, objects and adverbials naturally between the verbal brackets in ordinary German clauses.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "A2",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 41,
    prerequisites: ["de.sentence.verb-bracket", "de.case.accusative", "de.case.dative"],
    examples: ["Ich gebe meinem Bruder morgen das Buch.", "Ich habe es ihm gestern gegeben."],
  },
  {
    id: "de.sentence.object-pronoun-order",
    slug: "object-and-pronoun-order",
    title: "Object and pronoun order",
    shortDescription: "Order accusative and dative objects according to whether they are nouns or pronouns and according to information structure.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 42,
    prerequisites: ["de.sentence.mittelfeld-basics", "de.pronoun.accusative-dative"],
    examples: ["Ich gebe dem Kind das Buch.", "Ich gebe es dem Kind.", "Ich gebe es ihm."],
  },
  {
    id: "de.sentence.mittelfeld-complements-adverbials",
    slug: "mittelfeld-complements-and-adverbials",
    title: "Complements and adverbials in the Mittelfeld",
    shortDescription: "Distinguish Ergänzungen from Angaben and control their neutral and marked ordering in the Mittelfeld.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "B2",
    expectedBy: "B2",
    reinforcedAt: ["C1"],
    order: 51,
    prerequisites: ["de.sentence.mittelfeld-basics", "de.sentence.object-pronoun-order"],
    examples: ["Sie hat ihrem Kollegen gestern im Büro die Unterlagen gegeben."],
  },
  {
    id: "de.sentence.nachfeld-extraposition",
    slug: "nachfeld-and-extraposition",
    title: "Nachfeld and extraposition",
    shortDescription: "Place heavy clauses, comparisons and selected complements in the Nachfeld for clarity and information flow.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "C1",
    expectedBy: "C1",
    reinforcedAt: ["C2"],
    order: 61,
    prerequisites: ["de.sentence.complex-clause-order", "de.sentence.mittelfeld-complements-adverbials"],
    examples: ["Es ist wichtiger geworden, flexibel zu reagieren."],
  },
  {
    id: "de.sentence.information-structure",
    slug: "information-structure-and-focus",
    title: "Information structure and focus",
    shortDescription: "Use Vorfeld choice, Mittelfeld order and stress-sensitive placement to distinguish topic, given information, new information and focus.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "C1",
    expectedBy: "C2",
    order: 62,
    prerequisites: ["de.sentence.nachfeld-extraposition"],
  },
  {
    id: "de.sentence.marked-word-order",
    slug: "marked-word-order-and-stylistic-inversion",
    title: "Marked word order and stylistic inversion",
    shortDescription: "Interpret and deliberately use less neutral constituent orders for contrast, emphasis and sophisticated written style without violating German clause structure.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "C2",
    expectedBy: "C2",
    order: 63,
    prerequisites: ["de.sentence.information-structure"],
  },
  {
    id: "de.article.zero-article",
    slug: "zero-article",
    title: "Zero article",
    shortDescription: "Recognize when German normally omits an article with professions, nationalities, materials, abstract nouns, fixed expressions and some plural or mass-noun uses.",
    category: "ARTICLES",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 230,
    prerequisites: ["de.article.definite", "de.article.indefinite"],
    examples: ["Sie ist Ärztin.", "Ich trinke gern Kaffee.", "Er hat Angst."],
  },
  {
    id: "de.pronoun.indefinite",
    slug: "indefinite-pronouns",
    title: "Indefinite pronouns",
    shortDescription: "Use man, jemand, niemand, etwas, nichts and related forms for unspecified people and things.",
    category: "PRONOUNS",
    introducedAt: "A2",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 305,
    prerequisites: ["de.pronoun.personal"],
    examples: ["Man sagt, dass es morgen regnet.", "Niemand weiß etwas."],
  },
  {
    id: "de.pronoun.possessive-independent",
    slug: "independent-possessive-pronouns",
    title: "Independent possessive pronouns",
    shortDescription: "Use possessive forms independently when the noun is omitted.",
    category: "PRONOUNS",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 315,
    prerequisites: ["de.article.possessive-determiners"],
    examples: ["Ist das deiner?", "Das ist meins."],
  },
  {
    id: "de.pronoun.demonstrative",
    slug: "demonstrative-pronouns-and-determiners",
    title: "Demonstrative pronouns and determiners",
    shortDescription: "Use dieser, jener and demonstrative der/die/das forms to identify, contrast and refer back to people or things.",
    category: "PRONOUNS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 325,
    prerequisites: ["de.article.definite", "de.case.dative"],
    examples: ["Diese Jacke gefällt mir.", "Der da ist meiner."],
  },
  {
    id: "de.pronoun.reciprocal",
    slug: "reciprocal-pronouns",
    title: "Reciprocal pronouns",
    shortDescription: "Express reciprocal relationships with einander and reciprocal uses of sich.",
    category: "PRONOUNS",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 335,
    prerequisites: ["de.pronoun.reflexive"],
    examples: ["Sie helfen einander.", "Wir sehen uns morgen."],
  },
  {
    id: "de.verb.lassen",
    slug: "lassen-constructions",
    title: "lassen constructions",
    shortDescription: "Use lassen for causative, permissive and passive-like meanings.",
    category: "VERBS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 455,
    prerequisites: ["de.verb.modal", "de.sentence.verb-bracket"],
    examples: ["Ich lasse mein Fahrrad reparieren.", "Das lässt sich leicht erklären."],
  },
  {
    id: "de.verb.es-constructions",
    slug: "verbs-and-expressions-with-es",
    title: "Verbs and expressions with es",
    shortDescription: "Use obligatory, anticipatory and impersonal es in common verbal and adjectival constructions.",
    category: "VERBS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 461,
    examples: ["Es gibt viele Möglichkeiten.", "Es ist schwierig, das zu erklären.", "Es regnet."],
  },
  {
    id: "de.verb.modal-perfekt",
    slug: "modal-verbs-in-the-perfect",
    title: "Modal verbs in the Perfekt",
    shortDescription: "Form perfect constructions with modal verbs, including the Ersatzinfinitiv in double-infinitive structures.",
    category: "VERBS",
    introducedAt: "B2",
    expectedBy: "B2",
    reinforcedAt: ["C1"],
    order: 462,
    prerequisites: ["de.verb.modal", "de.tense.perfekt", "de.sentence.verb-bracket"],
    examples: ["Ich habe lange arbeiten müssen.", "Sie hat nicht kommen können."],
  },
  {
    id: "de.verb.modal-subjective",
    slug: "subjective-modal-verb-meanings",
    title: "Subjective meanings of modal verbs",
    shortDescription: "Use modal verbs to express probability, inference, hearsay and reported claims rather than obligation or ability.",
    category: "VERBS",
    introducedAt: "C1",
    expectedBy: "C1",
    reinforcedAt: ["C2"],
    order: 463,
    prerequisites: ["de.verb.modal", "de.tense.perfekt"],
    examples: ["Er muss schon angekommen sein.", "Sie soll sehr reich sein.", "Er will davon nichts gewusst haben."],
  },
  {
    id: "de.verb.functional-verb-constructions",
    slug: "functional-verb-constructions",
    title: "Functional verb constructions (Funktionsverbgefüge)",
    shortDescription: "Recognize and use noun-verb combinations common in formal German, such as eine Entscheidung treffen and zur Verfügung stehen.",
    category: "VERBS",
    introducedAt: "C1",
    expectedBy: "C2",
    order: 464,
    prerequisites: ["de.noun.nominalization"],
    examples: ["eine Entscheidung treffen", "in Betracht ziehen", "zur Verfügung stehen"],
  },
  {
    id: "de.verb.valency-advanced",
    slug: "advanced-valency-and-complement-patterns",
    title: "Advanced valency and complement patterns",
    shortDescription: "Control less common case, prepositional and clausal complement patterns and recognize register-dependent variants.",
    category: "VERBS",
    introducedAt: "C2",
    expectedBy: "C2",
    order: 465,
    prerequisites: ["de.verb.valency-case", "de.preposition.prepositional-verbs", "de.sentence.complex-clause-order"],
  },
  {
    id: "de.tense.future-ii",
    slug: "future-perfect-futur-ii",
    title: "Futur II",
    shortDescription: "Use werden + Partizip II + haben/sein for completed future events and retrospective probability or inference.",
    category: "TENSES",
    introducedAt: "B2",
    expectedBy: "C1",
    order: 541,
    prerequisites: ["de.tense.future", "de.tense.perfekt"],
    examples: ["Bis morgen wird er die Arbeit beendet haben.", "Sie wird schon angekommen sein."],
  },
  {
    id: "de.tense.narrative-shifts",
    slug: "advanced-narrative-tense-shifts",
    title: "Advanced narrative tense shifts",
    shortDescription: "Control deliberate shifts among Präsens, Präteritum, Perfekt and Plusquamperfekt in sophisticated narrative and stylistic contexts.",
    category: "TENSES",
    introducedAt: "C2",
    expectedBy: "C2",
    order: 542,
    prerequisites: ["de.tense.praeteritum-narrative", "de.tense.plusquamperfekt"],
  },
  {
    id: "de.negation.scope-advanced",
    slug: "advanced-negation-scope",
    title: "Advanced negation scope",
    shortDescription: "Control the scope of nicht and other negative expressions in complex clauses and distinguish sentence, constituent and contrastive negation.",
    category: "NEGATION",
    introducedAt: "C1",
    expectedBy: "C1",
    reinforcedAt: ["C2"],
    order: 611,
    prerequisites: ["de.negation.position", "de.sentence.complex-clause-order"],
    examples: ["Nicht alle Teilnehmer haben zugestimmt.", "Alle Teilnehmer haben nicht zugestimmt."],
  },
  {
    id: "de.preposition.temporal",
    slug: "temporal-prepositions",
    title: "Temporal prepositions",
    shortDescription: "Use temporal prepositions and their required cases to locate events in time and express duration or boundaries.",
    category: "PREPOSITIONS",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 705,
    prerequisites: ["de.case.dative", "de.case.genitive"],
    examples: ["seit einem Jahr", "während des Urlaubs", "innerhalb einer Woche", "außerhalb der Öffnungszeiten"],
  },
  {
    id: "de.preposition.ausser-dative",
    slug: "ausser-with-dative",
    title: "außer + dative",
    shortDescription: "Use außer with the dative to express exclusion and exceptions.",
    category: "PREPOSITIONS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 715,
    prerequisites: ["de.case.dative"],
    examples: ["Alle außer meinem Bruder kommen mit."],
  },
  {
    id: "de.preposition.abstract-relations",
    slug: "abstract-prepositional-relations",
    title: "Abstract prepositional relations",
    shortDescription: "Use prepositional phrases to express cause, purpose, contrast, means and conditions in increasingly formal language.",
    category: "PREPOSITIONS",
    introducedAt: "B2",
    expectedBy: "C1",
    order: 741,
    prerequisites: ["de.preposition.genitive", "de.preposition.prepositional-verbs"],
    examples: ["aufgrund des Wetters", "zum Zweck der Prüfung", "im Gegensatz zu", "mithilfe eines Programms"],
  },
  {
    id: "de.preposition.case-register-variation",
    slug: "preposition-case-and-register-variation",
    title: "Preposition case and register variation",
    shortDescription: "Recognize standard, colloquial and formal case variation after selected prepositions and choose forms appropriate to context.",
    category: "PREPOSITIONS",
    introducedAt: "C1",
    expectedBy: "C2",
    order: 742,
    prerequisites: ["de.preposition.genitive", "de.case.genitive"],
  },
  {
    id: "de.adjective.nominalized",
    slug: "nominalized-adjectives",
    title: "Adjectives used as nouns",
    shortDescription: "Use substantivized adjectives with appropriate capitalization and adjective endings.",
    category: "ADJECTIVES",
    secondaryCategories: ["NOUNS"],
    introducedAt: "B2",
    expectedBy: "B2",
    order: 821,
    prerequisites: ["de.adjective.declension"],
    examples: ["der Bekannte", "eine Deutsche", "die Arbeitslosen"],
  },
  {
    id: "de.adjective.participles",
    slug: "participles-as-adjectives",
    title: "Participles as adjectives",
    shortDescription: "Use Partizip I and Partizip II attributively and predicatively with normal adjective inflection where required.",
    category: "ADJECTIVES",
    introducedAt: "B2",
    expectedBy: "B2",
    reinforcedAt: ["C1"],
    order: 822,
    prerequisites: ["de.adjective.declension", "de.tense.perfekt"],
    examples: ["die wartenden Gäste", "die geschlossene Tür", "ein gut vorbereitetes Gespräch"],
  },
  {
    id: "de.adjective.extended-attributes",
    slug: "extended-adjective-and-participle-attributes",
    title: "Extended adjective and participle attributes",
    shortDescription: "Understand and produce expanded pre-nominal adjective and participle phrases common in formal written German.",
    category: "ADJECTIVES",
    introducedAt: "C1",
    expectedBy: "C2",
    order: 823,
    prerequisites: ["de.adjective.participles", "de.adjective.declension"],
    examples: ["die seit Jahren in Berlin lebenden Studierenden"],
  },
  {
    id: "de.conjunction.causal",
    slug: "causal-connections",
    title: "Causal connections",
    shortDescription: "Express reasons with weil, da, denn and causal linking adverbs such as deshalb, daher and deswegen.",
    category: "CONJUNCTIONS",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 911,
    prerequisites: ["de.conjunction.coordinating", "de.conjunction.subordinate-verb-final"],
    examples: ["Ich bleibe zu Hause, weil ich krank bin.", "Da es spät ist, gehen wir.", "Es regnet; deshalb bleiben wir zu Hause."],
  },
  {
    id: "de.conjunction.final",
    slug: "final-purpose-connections",
    title: "Final connections: goals and purposes",
    shortDescription: "Express goals and purposes with damit, sodass appropriate purpose formulations, and corresponding infinitive constructions.",
    category: "CONJUNCTIONS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 912,
    prerequisites: ["de.conjunction.subordinate-verb-final", "de.infinitive.um-ohne-statt"],
    examples: ["Ich spreche langsam, damit alle mich verstehen.", "Ich lerne viel, um die Prüfung zu bestehen."],
  },
  {
    id: "de.conjunction.conditional",
    slug: "conditional-connections",
    title: "Conditional connections",
    shortDescription: "Express real and hypothetical conditions with wenn, falls, sofern and related structures.",
    category: "CONJUNCTIONS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 913,
    prerequisites: ["de.conjunction.subordinate-verb-final"],
    examples: ["Falls du Zeit hast, ruf mich an.", "Wenn es regnet, bleiben wir zu Hause."],
  },
  {
    id: "de.conjunction.modal",
    slug: "modal-connections",
    title: "Modal connections: means and circumstances",
    shortDescription: "Express means and accompanying circumstances with indem, dadurch dass, ohne dass and equivalent infinitive patterns.",
    category: "CONJUNCTIONS",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 914,
    prerequisites: ["de.conjunction.subordinate-verb-final", "de.infinitive.um-ohne-statt"],
    examples: ["Man lernt, indem man übt.", "Er ging, ohne dass er sich verabschiedete."],
  },
  {
    id: "de.conjunction.adversative",
    slug: "adversative-connections",
    title: "Adversative connections",
    shortDescription: "Express contrasts with aber, während, wohingegen, jedoch, dagegen and related patterns.",
    category: "CONJUNCTIONS",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 915,
    prerequisites: ["de.conjunction.coordinating", "de.conjunction.subordinate-verb-final"],
    examples: ["Während er gern reist, bleibt sie lieber zu Hause.", "Er ist ruhig, wohingegen sein Bruder sehr lebhaft ist."],
  },
  {
    id: "de.conjunction.als-ob",
    slug: "als-ob-comparison-clauses",
    title: "Irreal comparison clauses with als ob",
    shortDescription: "Form unreal or distanced comparisons with als ob and Konjunktiv II.",
    category: "CONJUNCTIONS",
    secondaryCategories: ["SUBJUNCTIVE"],
    introducedAt: "B2",
    expectedBy: "B2",
    order: 941,
    prerequisites: ["de.subjunctive.konjunktiv-ii-hypothetical", "de.conjunction.subordinate-verb-final"],
    examples: ["Du tust so, als ob du keine Ahnung hättest."],
  },
  {
    id: "de.conjunction.advanced-register",
    slug: "advanced-connectors-and-register",
    title: "Advanced connectors and register",
    shortDescription: "Choose among semantically similar connectors according to syntax, register and rhetorical relation in formal speech and writing.",
    category: "CONJUNCTIONS",
    introducedAt: "C1",
    expectedBy: "C1",
    reinforcedAt: ["C2"],
    order: 942,
    prerequisites: ["de.conjunction.complex-connectors", "de.conjunction.causal", "de.conjunction.adversative"],
    examples: ["insofern", "sofern", "zumal", "wenngleich", "währenddessen", "demgegenüber"],
  },
  {
    id: "de.conjunction.discourse-cohesion",
    slug: "discourse-cohesion-and-linking",
    title: "Discourse cohesion and linking",
    shortDescription: "Use complex clause-linking and discourse-connective choices to manage concession, qualification, consequence, reformulation and argumentative progression across longer texts.",
    category: "CONJUNCTIONS",
    introducedAt: "C2",
    expectedBy: "C2",
    order: 943,
    prerequisites: ["de.conjunction.advanced-register"],
  },
  {
    id: "de.infinitive.brauchen-zu",
    slug: "brauchen-nicht-zu",
    title: "brauchen (nicht) + zu + infinitive",
    shortDescription: "Use brauchen + zu, especially with negation or restrictive expressions, to express lack of necessity.",
    category: "INFINITIVE_CONSTRUCTIONS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 1011,
    prerequisites: ["de.infinitive.zu", "de.negation.nicht-kein"],
    examples: ["Du brauchst nicht zu kommen."],
  },
  {
    id: "de.infinitive.perfect-passive",
    slug: "perfect-and-passive-infinitives",
    title: "Perfect and passive infinitives",
    shortDescription: "Use non-finite perfect and passive forms such as gemacht zu haben, gemacht zu werden and gemacht worden zu sein.",
    category: "INFINITIVE_CONSTRUCTIONS",
    introducedAt: "C1",
    expectedBy: "C2",
    order: 1021,
    prerequisites: ["de.infinitive.advanced", "de.passive.past", "de.tense.perfekt"],
    examples: ["Er behauptet, davon nichts gewusst zu haben.", "Das Problem scheint gelöst worden zu sein."],
  },
  {
    id: "de.infinitive.sein-haben-zu",
    slug: "sein-und-haben-zu-infinitive",
    title: "sein/haben + zu + infinitive",
    shortDescription: "Use sein + zu and haben + zu to express necessity, possibility and obligation in concise formal structures.",
    category: "INFINITIVE_CONSTRUCTIONS",
    introducedAt: "C1",
    expectedBy: "C1",
    reinforcedAt: ["C2"],
    order: 1022,
    prerequisites: ["de.infinitive.zu", "de.passive.alternatives"],
    examples: ["Die Aufgabe ist bis morgen zu erledigen.", "Wir haben noch viel zu klären."],
  },
  {
    id: "de.relative.genitive",
    slug: "genitive-relative-pronouns",
    parentId: "de.relative.basic",
    title: "Genitive relative pronouns dessen and deren",
    shortDescription: "Use dessen and deren to express possession and genitive relationships inside relative clauses.",
    category: "RELATIVE_CLAUSES",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1121,
    prerequisites: ["de.relative.basic", "de.case.genitive"],
    examples: ["Der Mann, dessen Auto gestohlen wurde, rief die Polizei."],
  },
  {
    id: "de.relative.free-relative",
    slug: "free-and-generalizing-relative-clauses",
    parentId: "de.relative.basic",
    title: "Free and generalizing relative clauses",
    shortDescription: "Use wer, was and related forms in relative clauses without an explicit nominal antecedent and in abstract reference.",
    category: "RELATIVE_CLAUSES",
    introducedAt: "C1",
    expectedBy: "C1",
    order: 1122,
    prerequisites: ["de.relative.was-wo"],
    examples: ["Wer zuerst kommt, bekommt den besten Platz.", "Was mich überrascht, ist seine Ruhe."],
  },
  {
    id: "de.relative.complex-embedding",
    slug: "complex-relative-clause-embedding",
    parentId: "de.relative.basic",
    title: "Complex relative-clause embedding",
    shortDescription: "Interpret and produce relative clauses embedded in dense noun phrases and multi-clause written structures while preserving clear reference.",
    category: "RELATIVE_CLAUSES",
    introducedAt: "C2",
    expectedBy: "C2",
    order: 1123,
    prerequisites: ["de.relative.genitive", "de.relative.prepositions", "de.sentence.complex-clause-order"],
  },
  {
    id: "de.passive.modal-verbs",
    slug: "passive-with-modal-verbs",
    parentId: "de.passive.present",
    title: "Passive with modal verbs",
    shortDescription: "Combine modal verbs with werden-passive while maintaining the German verbal bracket.",
    category: "PASSIVE",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 1201,
    prerequisites: ["de.passive.present", "de.verb.modal"],
    examples: ["Auf ausreichende Bewegung sollte geachtet werden."],
  },
  {
    id: "de.passive.impersonal",
    slug: "impersonal-passive",
    parentId: "de.passive.present",
    title: "Impersonal passive",
    shortDescription: "Form subjectless and es-supported passive clauses with intransitive verbs when German permits them.",
    category: "PASSIVE",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1202,
    prerequisites: ["de.passive.present"],
    examples: ["Es wird viel gearbeitet.", "Heute wird getanzt."],
  },
  {
    id: "de.passive.state",
    slug: "state-passive-zustandspassiv",
    parentId: "de.passive.present",
    title: "State passive (Zustandspassiv)",
    shortDescription: "Use sein + Partizip II to describe the resulting state of a completed action and distinguish it from werden-passive.",
    category: "PASSIVE",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1211,
    prerequisites: ["de.passive.present", "de.tense.perfekt"],
    examples: ["Die Tür ist geschlossen.", "Die Straße ist gesperrt."],
  },
  {
    id: "de.passive.agent-von-durch",
    slug: "passive-agent-von-durch",
    parentId: "de.passive.present",
    title: "Passive agents with von and durch",
    shortDescription: "Use von to introduce agents and durch to introduce means, causes or intermediaries where appropriate in passive clauses.",
    category: "PASSIVE",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1212,
    prerequisites: ["de.passive.present", "de.preposition.dative"],
    examples: ["Das Gebäude wurde von einem Architekten geplant.", "Die Straße wurde durch den Sturm blockiert."],
  },
  {
    id: "de.passive.bekommen",
    slug: "recipient-passive-bekommen",
    parentId: "de.passive.present",
    title: "Recipient passive with bekommen/kriegen/erhalten",
    shortDescription: "Recognize and use the recipient passive, especially with bekommen, to promote a dative recipient to subject position.",
    category: "PASSIVE",
    introducedAt: "C1",
    expectedBy: "C2",
    order: 1221,
    prerequisites: ["de.passive.present", "de.case.dative", "de.verb.valency-case"],
    examples: ["Sie bekommt die Unterlagen zugeschickt."],
  },
  {
    id: "de.subjunctive.konjunktiv-i-replacement",
    slug: "konjunktiv-i-replacement-forms",
    parentId: "de.subjunctive.konjunktiv-i-reporting",
    title: "Konjunktiv I replacement forms",
    shortDescription: "Use Konjunktiv II or würde forms when Konjunktiv I is ambiguous or identical to the indicative, especially in reported speech.",
    category: "SUBJUNCTIVE",
    introducedAt: "C1",
    expectedBy: "C1",
    order: 1331,
    prerequisites: ["de.subjunctive.konjunktiv-i-reporting", "de.subjunctive.konjunktiv-ii-hypothetical"],
  },
  {
    id: "de.subjunctive.indirect-speech-advanced",
    slug: "advanced-indirect-speech",
    parentId: "de.subjunctive.konjunktiv-i-reporting",
    title: "Advanced indirect speech",
    shortDescription: "Maintain tense, modality, pronoun reference and reporting distance across extended passages of indirect speech.",
    category: "SUBJUNCTIVE",
    introducedAt: "C1",
    expectedBy: "C2",
    order: 1332,
    prerequisites: ["de.subjunctive.konjunktiv-i-replacement", "de.tense.future-ii"],
  },
  {
    id: "de.subjunctive.register-nuance",
    slug: "subjunctive-register-and-stance",
    title: "Subjunctive register and stance",
    shortDescription: "Interpret and choose nuanced Konjunktiv I and II forms to signal distance, politeness, uncertainty, irreality and stylistic stance in sophisticated German.",
    category: "SUBJUNCTIVE",
    introducedAt: "C2",
    expectedBy: "C2",
    order: 1333,
    prerequisites: ["de.subjunctive.indirect-speech-advanced", "de.subjunctive.konjunktiv-ii-past"],
  },
  {
    id: "de.noun.gender",
    slug: "noun-gender-and-article",
    title: "Noun gender and article assignment",
    shortDescription: "Learn German nouns together with grammatical gender and recognize common gender patterns and productive suffix cues.",
    category: "NOUNS",
    secondaryCategories: ["ARTICLES"],
    introducedAt: "A1",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 1390,
    prerequisites: ["de.article.definite"],
    examples: ["der Tisch", "die Zeitung", "das Mädchen"],
  },
  {
    id: "de.noun.compounds",
    slug: "compound-nouns",
    title: "Compound nouns",
    shortDescription: "Build and interpret German compound nouns, including head-final gender and common linking elements.",
    category: "NOUNS",
    secondaryCategories: ["WORD_FORMATION"],
    introducedAt: "A2",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 1401,
    prerequisites: ["de.noun.gender"],
    examples: ["das Volksfest", "die Haustür", "der Arbeitsplatz"],
  },
  {
    id: "de.noun.genitive-attribute-chains",
    slug: "genitive-attribute-chains",
    title: "Complex genitive attributes",
    shortDescription: "Interpret and produce multi-part genitive attributes and alternatives with von in dense formal noun phrases.",
    category: "NOUNS",
    introducedAt: "C1",
    expectedBy: "C2",
    order: 1421,
    prerequisites: ["de.case.genitive", "de.noun.nominalization"],
  },
  {
    id: "de.noun.apposition",
    slug: "apposition",
    title: "Apposition",
    shortDescription: "Use close and loose apposition with appropriate case agreement and punctuation in formal and descriptive German.",
    category: "NOUNS",
    introducedAt: "C1",
    expectedBy: "C2",
    order: 1422,
    prerequisites: ["de.case.dative", "de.case.genitive"],
  },
  {
    id: "de.noun.nominal-style",
    slug: "dense-nominal-style",
    title: "Dense nominal style",
    shortDescription: "Understand and deliberately manage highly nominal written syntax, including chains of attributes, nominalizations and prepositional complements, while retaining clarity.",
    category: "NOUNS",
    secondaryCategories: ["WORD_FORMATION"],
    introducedAt: "C2",
    expectedBy: "C2",
    order: 1423,
    prerequisites: ["de.noun.nominalization", "de.noun.genitive-attribute-chains", "de.verb.functional-verb-constructions"],
  },
  {
    id: "de.particle.grad",
    slug: "degree-and-focus-particles",
    title: "Degree and focus particles",
    shortDescription: "Use particles and adverbs such as sehr, ziemlich, echt, besonders, sogar, nur and erst to grade or focus meanings.",
    category: "ADVERBS_PARTICLES",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 1500,
    examples: ["Das ist ziemlich schwierig.", "Sogar Anna hat zugestimmt."],
  },
  {
    id: "de.particle.modal",
    slug: "modal-particles",
    title: "Modal particles",
    shortDescription: "Understand and use common modal particles such as doch, ja, mal, eben, halt, wohl and denn to shape tone and shared assumptions.",
    category: "ADVERBS_PARTICLES",
    introducedAt: "B2",
    expectedBy: "C1",
    reinforcedAt: ["C2"],
    order: 1510,
    prerequisites: ["de.sentence.main-clause-v2"],
    examples: ["Komm doch mit!", "Das ist ja interessant.", "Was machst du denn?"],
  },
  {
    id: "de.particle.discourse-nuance",
    slug: "advanced-particle-and-discourse-nuance",
    title: "Advanced particle and discourse nuance",
    shortDescription: "Interpret subtle combinations of modal, focus and discourse particles and use them appropriately across colloquial, formal and literary registers.",
    category: "ADVERBS_PARTICLES",
    introducedAt: "C2",
    expectedBy: "C2",
    order: 1520,
    prerequisites: ["de.particle.modal", "de.particle.grad"],
  },
  {
    id: "de.wordformation.noun-derivation",
    slug: "noun-derivation",
    title: "Noun derivation",
    shortDescription: "Recognize and form common nouns using productive suffixes, prefixes and conversions.",
    category: "WORD_FORMATION",
    introducedAt: "B2",
    expectedBy: "B2",
    reinforcedAt: ["C1"],
    order: 1600,
    prerequisites: ["de.noun.nominalization"],
    examples: ["-ung", "-heit", "-keit", "-schaft", "-er"],
  },
  {
    id: "de.wordformation.adjective-verb",
    slug: "adjective-and-verb-derivation",
    title: "Adjective and verb derivation",
    shortDescription: "Recognize productive derivational patterns in adjectives and verbs, including common prefixes and suffixes that modify meaning and valency.",
    category: "WORD_FORMATION",
    introducedAt: "C1",
    expectedBy: "C1",
    reinforcedAt: ["C2"],
    order: 1610,
    prerequisites: ["de.verb.separable", "de.adjective.declension"],
  },
  {
    id: "de.wordformation.productive-advanced",
    slug: "advanced-productive-word-formation",
    title: "Advanced productive word formation",
    shortDescription: "Interpret and create less predictable compounds, derivations, nominalizations and lexicalized formations while judging register and acceptability.",
    category: "WORD_FORMATION",
    introducedAt: "C2",
    expectedBy: "C2",
    order: 1620,
    prerequisites: ["de.wordformation.noun-derivation", "de.wordformation.adjective-verb", "de.noun.compounds"],
  },

  {
    id: "de.article.quantifiers-determiners",
    slug: "quantifiers-and-determiners",
    title: "Quantifiers and determiners",
    shortDescription: "Use common quantity and distributive determiners such as alle, viele, wenige, einige, mehrere, beide and jeder with appropriate agreement.",
    category: "ARTICLES",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 231,
    prerequisites: ["de.article.definite", "de.article.indefinite"],
    examples: ["alle Kinder", "jeder Tag", "viele Menschen", "beide Seiten"],
  },
  {
    id: "de.pronoun.interrogative-case",
    slug: "interrogative-pronouns-and-case",
    title: "Interrogative pronouns and case",
    shortDescription: "Choose wer, wen, wem, wessen and prepositional question forms according to grammatical role and case.",
    category: "PRONOUNS",
    introducedAt: "A1",
    expectedBy: "A2",
    order: 301,
    prerequisites: ["de.sentence.w-questions", "de.case.accusative"],
    examples: ["Wer kommt?", "Wen siehst du?", "Wem hilfst du?", "Wessen Buch ist das?"],
  },
  {
    id: "de.verb.participle-ii-formation",
    slug: "past-participle-formation",
    title: "Past participle formation",
    shortDescription: "Form Partizip II for regular, strong, mixed, separable and inseparable verbs and recognize when ge- is absent.",
    category: "VERBS",
    introducedAt: "A2",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 431,
    prerequisites: ["de.verb.separable", "de.verb.present-regular"],
    examples: ["gemacht", "gegangen", "gebracht", "angerufen", "verstanden", "studiert"],
  },
  {
    id: "de.verb.inseparable-prefixes",
    slug: "inseparable-prefix-verbs",
    title: "Inseparable-prefix verbs",
    shortDescription: "Recognize common inseparable prefixes and their effects on stress, separability and past-participle formation.",
    category: "VERBS",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 432,
    prerequisites: ["de.verb.separable"],
    examples: ["verstehen", "besuchen", "erzählen", "verkaufen"],
  },
  {
    id: "de.verb.bare-infinitive",
    slug: "bare-infinitive-constructions",
    title: "Infinitive without zu",
    shortDescription: "Use bare infinitives after modal verbs and selected verbs such as lassen, sehen, hören and gehen where German does not use zu.",
    category: "VERBS",
    secondaryCategories: ["INFINITIVE_CONSTRUCTIONS"],
    introducedAt: "B1",
    expectedBy: "B2",
    order: 456,
    prerequisites: ["de.verb.modal", "de.verb.lassen"],
    examples: ["Ich muss arbeiten.", "Ich höre ihn singen.", "Wir gehen einkaufen."],
  },
  {
    id: "de.preposition.article-contractions",
    slug: "preposition-article-contractions",
    title: "Preposition–article contractions",
    shortDescription: "Use frequent contracted forms such as am, im, beim, vom, zum, zur, ins and ans where standard German requires or prefers them.",
    category: "PREPOSITIONS",
    secondaryCategories: ["ARTICLES"],
    introducedAt: "A1",
    expectedBy: "A2",
    order: 701,
    prerequisites: ["de.article.definite"],
    examples: ["im Haus", "am Montag", "zum Arzt", "ins Kino"],
  },
  {
    id: "de.conjunction.consecutive",
    slug: "consecutive-result-connections",
    title: "Consecutive connections: results and consequences",
    shortDescription: "Express results and consequences with sodass/so dass, daher, folglich and related linking patterns.",
    category: "CONJUNCTIONS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 916,
    prerequisites: ["de.conjunction.subordinate-verb-final", "de.conjunction.causal"],
    examples: ["Es regnete stark, sodass wir zu Hause blieben.", "Der Zug fiel aus; daher kamen wir später an."],
  },
  {
    id: "de.adverb.directional-hin-her",
    slug: "directional-adverbs-hin-her",
    title: "Directional adverbs with hin- and her-",
    shortDescription: "Use hin-, her- and related directional forms to distinguish movement away from or toward the speaker/reference point.",
    category: "ADVERBS_PARTICLES",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 1505,
    examples: ["Komm herein!", "Geh hinaus!", "Wo gehst du hin?", "Wo kommst du her?"],
  },
];

export function validateGrammarCurriculum(
  concepts: GrammarCurriculumConcept[] = grammarCurriculum,
): string[] {
  const errors: string[] = [];
  const byId = new Map<string, GrammarCurriculumConcept>();
  const slugs = new Set<string>();
  const orders = new Map<number, string>();

  for (const concept of concepts) {
    if (byId.has(concept.id)) errors.push(`Duplicate grammar concept id: ${concept.id}`);
    if (slugs.has(concept.slug)) errors.push(`Duplicate grammar concept slug: ${concept.slug}`);
    if (orders.has(concept.order)) {
      errors.push(`Duplicate grammar concept order ${concept.order}: ${orders.get(concept.order)} and ${concept.id}`);
    }
    byId.set(concept.id, concept);
    slugs.add(concept.slug);
    orders.set(concept.order, concept.id);

    if (concept.expectedBy && cefrRank[concept.expectedBy] < cefrRank[concept.introducedAt]) {
      errors.push(`${concept.id}: expectedBy cannot precede introducedAt`);
    }

    const reinforced = concept.reinforcedAt ?? [];
    if (new Set(reinforced).size !== reinforced.length) {
      errors.push(`${concept.id}: reinforcedAt contains duplicate levels`);
    }
    for (const level of reinforced) {
      if (cefrRank[level] <= cefrRank[concept.introducedAt]) {
        errors.push(`${concept.id}: reinforced level ${level} must follow introducedAt`);
      }
    }

    const secondary = concept.secondaryCategories ?? [];
    if (new Set(secondary).size !== secondary.length) {
      errors.push(`${concept.id}: secondaryCategories contains duplicates`);
    }
    if (secondary.includes(concept.category)) {
      errors.push(`${concept.id}: primary category must not also appear in secondaryCategories`);
    }
  }

  for (const concept of concepts) {
    const refs = [
      ...(concept.parentId ? [concept.parentId] : []),
      ...(concept.prerequisites ?? []),
      ...(concept.related ?? []).map((relation) => relation.targetId),
    ];
    for (const ref of refs) {
      if (!byId.has(ref)) errors.push(`${concept.id}: unknown grammar concept reference ${ref}`);
      if (ref === concept.id) errors.push(`${concept.id}: concept cannot reference itself`);
    }

    for (const prerequisiteId of concept.prerequisites ?? []) {
      const prerequisite = byId.get(prerequisiteId);
      if (prerequisite && cefrRank[prerequisite.introducedAt] > cefrRank[concept.introducedAt]) {
        errors.push(
          `${concept.id}: prerequisite ${prerequisiteId} is introduced later (${prerequisite.introducedAt}) than the concept (${concept.introducedAt})`,
        );
      }
    }
  }

  function detectCycles(edgeType: "prerequisite" | "parent") {
    const visiting = new Set<string>();
    const visited = new Set<string>();

    function visit(id: string, path: string[]) {
      if (visiting.has(id)) {
        errors.push(`Grammar ${edgeType} cycle: ${[...path, id].join(" -> ")}`);
        return;
      }
      if (visited.has(id)) return;

      visiting.add(id);
      const concept = byId.get(id);
      const next = edgeType === "prerequisite"
        ? concept?.prerequisites ?? []
        : concept?.parentId
          ? [concept.parentId]
          : [];
      for (const targetId of next) visit(targetId, [...path, id]);
      visiting.delete(id);
      visited.add(id);
    }

    for (const concept of concepts) visit(concept.id, []);
  }

  detectCycles("prerequisite");
  detectCycles("parent");

  return [...new Set(errors)];
}

export function assertValidGrammarCurriculum(
  concepts: GrammarCurriculumConcept[] = grammarCurriculum,
) {
  const errors = validateGrammarCurriculum(concepts);
  if (errors.length > 0) {
    throw new Error(`Invalid grammar curriculum:\n- ${errors.join("\n- ")}`);
  }
}
