export const CEFR_LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"] as const;
export type CefrLevelCode = (typeof CEFR_LEVELS)[number];

export const GRAMMAR_CATEGORIES = [
  "SENTENCE_STRUCTURE",
  "CASES",
  "VERBS",
  "TENSES",
  "ARTICLES",
  "ADJECTIVES",
  "PREPOSITIONS",
  "PRONOUNS",
  "CONJUNCTIONS",
  "RELATIVE_CLAUSES",
  "NEGATION",
  "COMPARISON",
  "PASSIVE",
  "SUBJUNCTIVE",
  "INFINITIVE_CONSTRUCTIONS",
  "NOUNS",
] as const;

export type GrammarCategoryCode = (typeof GRAMMAR_CATEGORIES)[number];
export type GrammarRelationCode = "RELATED" | "CONTRASTS_WITH" | "EXTENDS";

export type GrammarCurriculumConcept = {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  category: GrammarCategoryCode;
  introducedAt: CefrLevelCode;
  expectedBy?: CefrLevelCode;
  reinforcedAt?: CefrLevelCode[];
  parentId?: string;
  order: number;
  explanation?: string;
  rules?: string[];
  exceptions?: string[];
  examples?: string[];
  prerequisites?: string[];
  related?: Array<{ targetId: string; type?: GrammarRelationCode }>;
};

export const cefrRank: Record<CefrLevelCode, number> = {
  A1: 1,
  A2: 2,
  B1: 3,
  B2: 4,
  C1: 5,
  C2: 6,
};

export const grammarCurriculum: GrammarCurriculumConcept[] = [
  {
    id: "de.sentence.main-clause-v2",
    slug: "main-clause-v2",
    title: "Main-clause V2 word order",
    shortDescription: "Place the finite verb in the second syntactic position of a German main clause.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "A1",
    expectedBy: "A1",
    reinforcedAt: ["A2", "B1"],
    order: 10,
    rules: ["The finite verb occupies position two.", "Another constituent may occupy position one."],
    examples: ["Ich lerne heute Deutsch.", "Heute lerne ich Deutsch."],
  },
  {
    id: "de.sentence.yes-no-questions",
    slug: "yes-no-questions",
    title: "Yes/no questions",
    shortDescription: "Form yes/no questions with the finite verb in first position.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "A1",
    expectedBy: "A1",
    order: 20,
    prerequisites: ["de.sentence.main-clause-v2"],
    examples: ["Kommst du morgen?", "Hast du Zeit?"],
  },
  {
    id: "de.sentence.w-questions",
    slug: "w-questions",
    title: "W-questions",
    shortDescription: "Form information questions with an interrogative element followed by the finite verb.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "A1",
    expectedBy: "A1",
    order: 30,
    prerequisites: ["de.sentence.main-clause-v2"],
    examples: ["Wo wohnst du?", "Warum lernst du Deutsch?"],
  },
  {
    id: "de.sentence.time-manner-place",
    slug: "time-manner-place",
    title: "Time–manner–place ordering",
    shortDescription: "Use the common neutral ordering of adverbial information in German clauses.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "A2",
    expectedBy: "B1",
    reinforcedAt: ["B1", "B2"],
    order: 40,
    prerequisites: ["de.sentence.main-clause-v2"],
    examples: ["Ich fahre morgen mit dem Zug nach Berlin."],
  },
  {
    id: "de.sentence.indirect-questions",
    slug: "indirect-questions",
    title: "Indirect questions",
    shortDescription: "Embed questions with ob or an interrogative word and subordinate-clause word order.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 50,
    prerequisites: ["de.conjunction.subordinate-verb-final", "de.sentence.w-questions"],
    examples: ["Ich weiß nicht, ob er kommt.", "Kannst du mir sagen, wo sie wohnt?"],
  },
  {
    id: "de.sentence.complex-clause-order",
    slug: "complex-clause-order",
    title: "Complex clause ordering",
    shortDescription: "Combine multiple main and subordinate clauses while preserving verb placement and clear information flow.",
    category: "SENTENCE_STRUCTURE",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 60,
    prerequisites: ["de.conjunction.subordinate-verb-final", "de.conjunction.complex-connectors"],
  },

  {
    id: "de.case.nominative",
    slug: "nominative-case",
    title: "Nominative case",
    shortDescription: "Use nominative forms for subjects and predicate nouns.",
    category: "CASES",
    introducedAt: "A1",
    expectedBy: "A1",
    order: 100,
    examples: ["Der Mann arbeitet.", "Das ist ein Problem."],
  },
  {
    id: "de.case.accusative",
    slug: "accusative-case",
    title: "Accusative case",
    shortDescription: "Use accusative forms for many direct objects and after accusative-governing prepositions.",
    category: "CASES",
    introducedAt: "A1",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 110,
    prerequisites: ["de.case.nominative", "de.article.definite"],
    examples: ["Ich sehe den Mann.", "Sie kauft einen Kaffee."],
  },
  {
    id: "de.case.dative",
    slug: "dative-case",
    title: "Dative case",
    shortDescription: "Use dative forms for many indirect objects, verbs and prepositions that govern dative.",
    category: "CASES",
    introducedAt: "A2",
    expectedBy: "A2",
    reinforcedAt: ["B1", "B2"],
    order: 120,
    prerequisites: ["de.case.accusative", "de.article.definite"],
    examples: ["Ich helfe dem Mann.", "Sie spricht mit ihrer Freundin."],
  },
  {
    id: "de.case.genitive",
    slug: "genitive-case",
    title: "Genitive case",
    shortDescription: "Use genitive for possession and with selected formal prepositions and constructions.",
    category: "CASES",
    introducedAt: "B1",
    expectedBy: "B2",
    reinforcedAt: ["B2"],
    order: 130,
    prerequisites: ["de.case.dative"],
    examples: ["Wegen des Wetters bleiben wir zu Hause.", "Das ist das Auto meines Bruders."],
  },
  {
    id: "de.case.two-way-prepositions",
    slug: "two-way-prepositions",
    title: "Two-way prepositions",
    shortDescription: "Choose accusative or dative after Wechselpräpositionen according to directional vs. locative meaning.",
    category: "CASES",
    introducedAt: "A2",
    expectedBy: "B1",
    reinforcedAt: ["B1", "B2"],
    order: 140,
    prerequisites: ["de.case.accusative", "de.case.dative"],
    related: [{ targetId: "de.preposition.two-way", type: "RELATED" }],
    examples: ["Ich gehe in die Küche.", "Ich bin in der Küche."],
  },

  {
    id: "de.article.definite",
    slug: "definite-articles",
    title: "Definite articles",
    shortDescription: "Use der, die, das and their case forms with definite noun phrases.",
    category: "ARTICLES",
    introducedAt: "A1",
    expectedBy: "A1",
    reinforcedAt: ["A2"],
    order: 200,
    examples: ["der Tisch", "die Stadt", "das Buch"],
  },
  {
    id: "de.article.indefinite",
    slug: "indefinite-articles",
    title: "Indefinite articles",
    shortDescription: "Use ein/eine and their case forms with indefinite noun phrases.",
    category: "ARTICLES",
    introducedAt: "A1",
    expectedBy: "A1",
    reinforcedAt: ["A2"],
    order: 210,
    prerequisites: ["de.article.definite"],
    examples: ["ein Tisch", "eine Stadt", "ein Buch"],
  },
  {
    id: "de.article.possessive-determiners",
    slug: "possessive-determiners",
    title: "Possessive determiners",
    shortDescription: "Use mein, dein, sein, ihr and related forms with case and gender agreement.",
    category: "ARTICLES",
    introducedAt: "A1",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 220,
    prerequisites: ["de.article.indefinite"],
    examples: ["mein Bruder", "mit meiner Freundin"],
  },

  {
    id: "de.pronoun.personal",
    slug: "personal-pronouns",
    title: "Personal pronouns",
    shortDescription: "Use German subject pronouns and distinguish person, number and formal Sie.",
    category: "PRONOUNS",
    introducedAt: "A1",
    expectedBy: "A1",
    order: 300,
    examples: ["ich", "du", "er", "sie", "es", "wir", "ihr", "Sie"],
  },
  {
    id: "de.pronoun.accusative-dative",
    slug: "accusative-dative-pronouns",
    title: "Accusative and dative pronouns",
    shortDescription: "Choose object-pronoun forms such as mich/mir and ihn/ihm according to case.",
    category: "PRONOUNS",
    introducedAt: "A2",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 310,
    prerequisites: ["de.pronoun.personal", "de.case.accusative", "de.case.dative"],
    examples: ["Er sieht mich.", "Er hilft mir."],
  },
  {
    id: "de.pronoun.reflexive",
    slug: "reflexive-pronouns",
    title: "Reflexive pronouns",
    shortDescription: "Use reflexive pronouns with reflexive verbs and reflexive meanings.",
    category: "PRONOUNS",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 320,
    prerequisites: ["de.pronoun.accusative-dative"],
    examples: ["Ich erinnere mich.", "Sie wäscht sich die Hände."],
  },
  {
    id: "de.pronoun.da-wo-compounds",
    slug: "da-wo-compounds",
    title: "Da-/wo- compounds",
    shortDescription: "Use daran, damit, worauf and related forms for things and clauses with prepositions.",
    category: "PRONOUNS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 330,
    prerequisites: ["de.preposition.prepositional-verbs"],
    examples: ["Ich denke daran.", "Worauf wartest du?"],
  },

  {
    id: "de.verb.present-regular",
    slug: "present-tense",
    title: "Present tense",
    shortDescription: "Conjugate regular and common irregular verbs in Präsens.",
    category: "VERBS",
    introducedAt: "A1",
    expectedBy: "A1",
    reinforcedAt: ["A2"],
    order: 400,
    examples: ["ich lerne", "du arbeitest", "er fährt"],
  },
  {
    id: "de.verb.sein-haben",
    slug: "sein-haben-present",
    title: "sein and haben",
    shortDescription: "Use the highly irregular present-tense forms of sein and haben.",
    category: "VERBS",
    introducedAt: "A1",
    expectedBy: "A1",
    order: 410,
    examples: ["Ich bin müde.", "Wir haben Zeit."],
  },
  {
    id: "de.verb.modal",
    slug: "modal-verbs",
    title: "Modal verbs",
    shortDescription: "Use modal verbs with a finite modal and infinitive at the end of the clause.",
    category: "VERBS",
    introducedAt: "A1",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 420,
    prerequisites: ["de.verb.present-regular", "de.sentence.main-clause-v2"],
    examples: ["Ich muss heute arbeiten.", "Wir können morgen kommen."],
  },
  {
    id: "de.verb.separable",
    slug: "separable-verbs",
    title: "Separable verbs",
    shortDescription: "Separate verb prefixes in finite main clauses and keep them joined in appropriate non-finite forms.",
    category: "VERBS",
    introducedAt: "A1",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 430,
    prerequisites: ["de.verb.present-regular", "de.sentence.main-clause-v2"],
    examples: ["Ich stehe um sieben Uhr auf.", "Ich möchte früh aufstehen."],
  },
  {
    id: "de.verb.imperative",
    slug: "imperative",
    title: "Imperative",
    shortDescription: "Form informal and formal commands and requests.",
    category: "VERBS",
    introducedAt: "A1",
    expectedBy: "A2",
    order: 440,
    prerequisites: ["de.verb.present-regular"],
    examples: ["Komm bitte!", "Kommen Sie bitte herein!"],
  },
  {
    id: "de.verb.reflexive",
    slug: "reflexive-verbs",
    title: "Reflexive verbs",
    shortDescription: "Use common reflexive verbs with the appropriate reflexive pronoun and case.",
    category: "VERBS",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 450,
    prerequisites: ["de.pronoun.reflexive"],
    examples: ["Ich interessiere mich für Musik.", "Sie erinnert sich an den Termin."],
  },
  {
    id: "de.verb.valency-case",
    slug: "verb-case-government",
    title: "Verb case government",
    shortDescription: "Learn verbs that require dative, accusative or particular argument structures.",
    category: "VERBS",
    introducedAt: "A2",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 460,
    prerequisites: ["de.case.accusative", "de.case.dative"],
    examples: ["jemandem helfen", "jemandem danken", "jemanden fragen"],
  },

  {
    id: "de.tense.perfekt",
    slug: "perfekt",
    title: "Perfekt",
    shortDescription: "Form the conversational past with haben/sein and the past participle.",
    category: "TENSES",
    introducedAt: "A2",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 500,
    prerequisites: ["de.verb.present-regular", "de.verb.sein-haben"],
    examples: ["Ich habe gearbeitet.", "Sie ist nach Hause gegangen."],
  },
  {
    id: "de.tense.praeteritum-core",
    slug: "praeteritum-core-verbs",
    title: "Präteritum of core verbs",
    shortDescription: "Use common simple-past forms, especially sein, haben and modal verbs.",
    category: "TENSES",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 510,
    prerequisites: ["de.verb.sein-haben", "de.verb.modal"],
    examples: ["Ich war müde.", "Wir hatten keine Zeit.", "Er musste gehen."],
  },
  {
    id: "de.tense.praeteritum-narrative",
    slug: "praeteritum-narrative",
    title: "Narrative Präteritum",
    shortDescription: "Use a wider range of simple-past verb forms in written narrative and formal contexts.",
    category: "TENSES",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 520,
    prerequisites: ["de.tense.praeteritum-core"],
    examples: ["Er öffnete die Tür und ging hinein."],
  },
  {
    id: "de.tense.plusquamperfekt",
    slug: "plusquamperfekt",
    title: "Plusquamperfekt",
    shortDescription: "Express an event completed before another past event.",
    category: "TENSES",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 530,
    prerequisites: ["de.tense.perfekt", "de.tense.praeteritum-core"],
    examples: ["Nachdem ich gegessen hatte, ging ich spazieren."],
  },
  {
    id: "de.tense.future",
    slug: "future-werden",
    title: "Future with werden",
    shortDescription: "Use werden + infinitive for future reference and selected modal meanings.",
    category: "TENSES",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 540,
    prerequisites: ["de.verb.present-regular"],
    examples: ["Ich werde morgen anrufen."],
  },

  {
    id: "de.negation.nicht-kein",
    slug: "nicht-and-kein",
    title: "Negation with nicht and kein",
    shortDescription: "Choose nicht or kein and place negation appropriately in simple clauses.",
    category: "NEGATION",
    introducedAt: "A1",
    expectedBy: "A1",
    reinforcedAt: ["A2", "B1"],
    order: 600,
    prerequisites: ["de.article.indefinite"],
    examples: ["Ich komme heute nicht.", "Ich habe kein Auto."],
  },
  {
    id: "de.negation.position",
    slug: "negation-position",
    title: "Advanced negation placement",
    shortDescription: "Place nicht according to the constituent or scope being negated.",
    category: "NEGATION",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 610,
    prerequisites: ["de.negation.nicht-kein", "de.sentence.main-clause-v2"],
  },

  {
    id: "de.preposition.accusative",
    slug: "accusative-prepositions",
    title: "Accusative prepositions",
    shortDescription: "Use common prepositions that consistently govern the accusative case.",
    category: "PREPOSITIONS",
    introducedAt: "A1",
    expectedBy: "A2",
    order: 700,
    prerequisites: ["de.case.accusative"],
    examples: ["für dich", "ohne einen Termin", "durch den Park"],
  },
  {
    id: "de.preposition.dative",
    slug: "dative-prepositions",
    title: "Dative prepositions",
    shortDescription: "Use common prepositions that consistently govern the dative case.",
    category: "PREPOSITIONS",
    introducedAt: "A2",
    expectedBy: "A2",
    order: 710,
    prerequisites: ["de.case.dative"],
    examples: ["mit dem Zug", "bei meiner Freundin", "nach der Arbeit"],
  },
  {
    id: "de.preposition.two-way",
    slug: "two-way-preposition-usage",
    title: "Two-way preposition usage",
    shortDescription: "Use an, auf, hinter, in, neben, über, unter, vor and zwischen with case determined by meaning.",
    category: "PREPOSITIONS",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 720,
    prerequisites: ["de.preposition.accusative", "de.preposition.dative"],
    related: [{ targetId: "de.case.two-way-prepositions", type: "RELATED" }],
  },
  {
    id: "de.preposition.prepositional-verbs",
    slug: "prepositional-verbs",
    title: "Prepositional verbs",
    shortDescription: "Learn verb + preposition + case combinations as lexical patterns.",
    category: "PREPOSITIONS",
    introducedAt: "A2",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 730,
    prerequisites: ["de.case.accusative", "de.case.dative"],
    examples: ["warten auf + Akk.", "teilnehmen an + Dat.", "abhängen von + Dat."],
  },
  {
    id: "de.preposition.genitive",
    slug: "genitive-prepositions",
    title: "Genitive prepositions",
    shortDescription: "Use selected formal prepositions with genitive, while recognizing common register variation.",
    category: "PREPOSITIONS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 740,
    prerequisites: ["de.case.genitive"],
    examples: ["wegen des Wetters", "trotz des Problems", "während des Urlaubs"],
  },

  {
    id: "de.adjective.predicative",
    slug: "predicative-adjectives",
    title: "Predicative adjectives",
    shortDescription: "Use uninflected adjectives after verbs such as sein, werden and bleiben.",
    category: "ADJECTIVES",
    introducedAt: "A1",
    expectedBy: "A1",
    order: 800,
    examples: ["Das Buch ist interessant."],
  },
  {
    id: "de.adjective.endings-basic",
    slug: "adjective-endings-basic",
    title: "Basic adjective endings",
    shortDescription: "Use common adjective endings in frequent nominative and accusative noun phrases.",
    category: "ADJECTIVES",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 810,
    prerequisites: ["de.article.definite", "de.article.indefinite", "de.case.accusative"],
    examples: ["ein gutes Buch", "den neuen Film"],
  },
  {
    id: "de.adjective.declension",
    slug: "adjective-declension",
    title: "Adjective declension",
    shortDescription: "Choose weak, mixed and strong adjective endings across gender, number and case.",
    category: "ADJECTIVES",
    introducedAt: "B1",
    expectedBy: "B2",
    reinforcedAt: ["B2"],
    order: 820,
    prerequisites: ["de.adjective.endings-basic", "de.case.dative", "de.case.genitive"],
    examples: ["mit einem guten Freund", "frisches Brot", "die neuen Regeln"],
  },
  {
    id: "de.comparison.comparative-superlative",
    slug: "comparative-superlative",
    title: "Comparative and superlative",
    shortDescription: "Form and use comparative and superlative adjectives and adverbs.",
    category: "COMPARISON",
    introducedAt: "A2",
    expectedBy: "A2",
    reinforcedAt: ["B1"],
    order: 850,
    examples: ["schneller", "am schnellsten", "größer als"],
  },

  {
    id: "de.conjunction.coordinating",
    slug: "coordinating-conjunctions",
    title: "Coordinating conjunctions",
    shortDescription: "Connect clauses with und, aber, oder, denn and sondern without changing main-clause verb position.",
    category: "CONJUNCTIONS",
    introducedAt: "A1",
    expectedBy: "A2",
    order: 900,
    prerequisites: ["de.sentence.main-clause-v2"],
    examples: ["Ich komme, aber ich bleibe nicht lange."],
  },
  {
    id: "de.conjunction.subordinate-verb-final",
    slug: "subordinate-clause-word-order",
    title: "Subordinate-clause verb-final order",
    shortDescription: "Move the finite verb to the end of clauses introduced by subordinating conjunctions.",
    category: "CONJUNCTIONS",
    introducedAt: "A2",
    expectedBy: "B1",
    reinforcedAt: ["B1", "B2"],
    order: 910,
    prerequisites: ["de.sentence.main-clause-v2"],
    examples: ["Ich bleibe zu Hause, weil ich krank bin.", "Ich weiß, dass er heute kommt."],
  },
  {
    id: "de.conjunction.temporal",
    slug: "temporal-conjunctions",
    title: "Temporal conjunctions",
    shortDescription: "Express time relations with als, wenn, bevor, nachdem, während, seitdem and similar connectors.",
    category: "CONJUNCTIONS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 920,
    prerequisites: ["de.conjunction.subordinate-verb-final"],
    examples: ["Nachdem ich gegessen hatte, ging ich spazieren."],
  },
  {
    id: "de.conjunction.concession",
    slug: "concessive-connections",
    title: "Concession with obwohl and trotzdem",
    shortDescription: "Contrast facts using subordinate and main-clause connective patterns.",
    category: "CONJUNCTIONS",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 930,
    prerequisites: ["de.conjunction.subordinate-verb-final"],
    examples: ["Obwohl es regnet, gehen wir spazieren.", "Es regnet. Trotzdem gehen wir spazieren."],
  },
  {
    id: "de.conjunction.complex-connectors",
    slug: "complex-connectors",
    title: "Complex connectors",
    shortDescription: "Use paired and formal connectors to structure contrast, cause, consequence and alternatives.",
    category: "CONJUNCTIONS",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 940,
    prerequisites: ["de.conjunction.coordinating", "de.conjunction.subordinate-verb-final"],
    examples: ["nicht nur … sondern auch", "einerseits … andererseits", "sowohl … als auch"],
  },

  {
    id: "de.infinitive.zu",
    slug: "infinitive-with-zu",
    title: "Infinitive clauses with zu",
    shortDescription: "Use zu + infinitive with verbs, adjectives and noun expressions that license an infinitive clause.",
    category: "INFINITIVE_CONSTRUCTIONS",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 1000,
    prerequisites: ["de.verb.present-regular"],
    examples: ["Ich versuche, früher zu schlafen.", "Es ist wichtig, pünktlich zu sein."],
  },
  {
    id: "de.infinitive.um-ohne-statt",
    slug: "um-ohne-statt-zu",
    title: "um/ohne/statt … zu",
    shortDescription: "Express purpose or accompanying circumstances with infinitive constructions.",
    category: "INFINITIVE_CONSTRUCTIONS",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 1010,
    prerequisites: ["de.infinitive.zu"],
    examples: ["Ich lerne viel, um die Prüfung zu bestehen."],
  },
  {
    id: "de.infinitive.advanced",
    slug: "advanced-infinitive-constructions",
    title: "Advanced infinitive constructions",
    shortDescription: "Use expanded infinitive groups and select between infinitive and finite subordinate clauses.",
    category: "INFINITIVE_CONSTRUCTIONS",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1020,
    prerequisites: ["de.infinitive.um-ohne-statt", "de.conjunction.subordinate-verb-final"],
  },

  {
    id: "de.relative.basic",
    slug: "relative-clauses",
    title: "Relative clauses",
    shortDescription: "Form relative clauses with case-marked relative pronouns and verb-final order.",
    category: "RELATIVE_CLAUSES",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 1100,
    prerequisites: ["de.case.accusative", "de.case.dative", "de.conjunction.subordinate-verb-final"],
    examples: ["Das ist der Mann, der hier arbeitet.", "Das ist die Frau, die ich kenne."],
  },
  {
    id: "de.relative.prepositions",
    slug: "relative-pronouns-with-prepositions",
    title: "Relative pronouns with prepositions",
    shortDescription: "Choose relative-pronoun case after prepositions inside relative clauses.",
    category: "RELATIVE_CLAUSES",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1110,
    prerequisites: ["de.relative.basic", "de.preposition.prepositional-verbs"],
    examples: ["Das ist das Thema, über das wir gesprochen haben."],
  },
  {
    id: "de.relative.was-wo",
    slug: "relative-was-wo",
    title: "Relative clauses with was and wo",
    shortDescription: "Use was and wo in common relative constructions after pronouns, clauses and place expressions.",
    category: "RELATIVE_CLAUSES",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1120,
    prerequisites: ["de.relative.basic"],
  },

  {
    id: "de.passive.present",
    slug: "passive-present",
    title: "Process passive in the present",
    shortDescription: "Form Vorgangspassiv with werden + past participle.",
    category: "PASSIVE",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 1200,
    prerequisites: ["de.verb.present-regular", "de.tense.perfekt"],
    examples: ["Das Haus wird gebaut."],
  },
  {
    id: "de.passive.past",
    slug: "passive-past",
    title: "Passive in past tenses",
    shortDescription: "Use passive constructions in Präteritum and Perfekt.",
    category: "PASSIVE",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 1210,
    prerequisites: ["de.passive.present", "de.tense.praeteritum-core"],
    examples: ["Das Haus wurde gebaut.", "Das Haus ist gebaut worden."],
  },
  {
    id: "de.passive.alternatives",
    slug: "passive-alternatives",
    title: "Alternatives to the passive",
    shortDescription: "Use man, sich lassen and sein + zu constructions where German prefers alternatives to werden-passive.",
    category: "PASSIVE",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1220,
    prerequisites: ["de.passive.present", "de.infinitive.zu"],
  },

  {
    id: "de.subjunctive.konjunktiv-ii-polite",
    slug: "konjunktiv-ii-polite",
    title: "Konjunktiv II for polite requests",
    shortDescription: "Use würde, hätte, wäre and modal subjunctive forms for polite and softened requests.",
    category: "SUBJUNCTIVE",
    introducedAt: "A2",
    expectedBy: "B1",
    order: 1300,
    prerequisites: ["de.verb.modal", "de.verb.sein-haben"],
    examples: ["Könnten Sie mir helfen?", "Ich hätte gern einen Kaffee."],
  },
  {
    id: "de.subjunctive.konjunktiv-ii-hypothetical",
    slug: "konjunktiv-ii-hypothetical",
    title: "Konjunktiv II for hypothetical situations",
    shortDescription: "Express unreal, hypothetical and wished-for situations with Konjunktiv II.",
    category: "SUBJUNCTIVE",
    introducedAt: "B1",
    expectedBy: "B1",
    reinforcedAt: ["B2"],
    order: 1310,
    prerequisites: ["de.subjunctive.konjunktiv-ii-polite", "de.conjunction.subordinate-verb-final"],
    examples: ["Wenn ich mehr Zeit hätte, würde ich mehr lesen."],
  },
  {
    id: "de.subjunctive.konjunktiv-ii-past",
    slug: "konjunktiv-ii-past",
    title: "Past Konjunktiv II",
    shortDescription: "Express unreal past conditions, regrets and counterfactual outcomes.",
    category: "SUBJUNCTIVE",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1320,
    prerequisites: ["de.subjunctive.konjunktiv-ii-hypothetical", "de.tense.perfekt"],
    examples: ["Wenn ich das gewusst hätte, wäre ich früher gekommen."],
  },
  {
    id: "de.subjunctive.konjunktiv-i-reporting",
    slug: "konjunktiv-i-reported-speech",
    title: "Konjunktiv I in reported speech",
    shortDescription: "Recognize and use Konjunktiv I for indirect reporting, especially in formal written German.",
    category: "SUBJUNCTIVE",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1330,
    prerequisites: ["de.verb.present-regular", "de.sentence.complex-clause-order"],
    examples: ["Er sagte, er habe keine Zeit."],
  },

  {
    id: "de.noun.plural",
    slug: "noun-plurals",
    title: "Noun plural patterns",
    shortDescription: "Recognize and produce common German plural patterns as lexical information.",
    category: "NOUNS",
    introducedAt: "A1",
    expectedBy: "A2",
    order: 1400,
    examples: ["der Tisch → die Tische", "die Stadt → die Städte"],
  },
  {
    id: "de.noun.weak-nouns",
    slug: "weak-nouns",
    title: "Weak masculine nouns",
    shortDescription: "Use n-declension endings for common weak masculine nouns outside nominative singular.",
    category: "NOUNS",
    introducedAt: "B1",
    expectedBy: "B2",
    order: 1410,
    prerequisites: ["de.case.accusative", "de.case.dative", "de.case.genitive"],
    examples: ["der Student → mit dem Studenten"],
  },
  {
    id: "de.noun.nominalization",
    slug: "nominalization",
    title: "Nominalization",
    shortDescription: "Recognize and form common nominalized verbs and adjectives in formal and abstract language.",
    category: "NOUNS",
    introducedAt: "B2",
    expectedBy: "B2",
    order: 1420,
    prerequisites: ["de.adjective.declension"],
    examples: ["das Lesen", "die Arbeitslosen"],
  },
];

export function validateGrammarCurriculum(
  concepts: GrammarCurriculumConcept[] = grammarCurriculum,
): string[] {
  const errors: string[] = [];
  const byId = new Map<string, GrammarCurriculumConcept>();
  const slugs = new Set<string>();

  for (const concept of concepts) {
    if (byId.has(concept.id)) errors.push(`Duplicate grammar concept id: ${concept.id}`);
    if (slugs.has(concept.slug)) errors.push(`Duplicate grammar concept slug: ${concept.slug}`);
    byId.set(concept.id, concept);
    slugs.add(concept.slug);

    if (concept.expectedBy && cefrRank[concept.expectedBy] < cefrRank[concept.introducedAt]) {
      errors.push(`${concept.id}: expectedBy cannot precede introducedAt`);
    }
    for (const level of concept.reinforcedAt ?? []) {
      if (cefrRank[level] < cefrRank[concept.introducedAt]) {
        errors.push(`${concept.id}: reinforced level ${level} precedes introducedAt`);
      }
    }
  }

  for (const concept of concepts) {
    const refs = [
      ...(concept.parentId ? [concept.parentId] : []),
      ...(concept.prerequisites ?? []),
      ...(concept.related ?? []).map((relation) => relation.targetId),
    ];
    for (const ref of refs) {
      if (!byId.has(ref)) errors.push(`${concept.id}: unknown grammar concept reference ${ref}`);
      if (ref === concept.id) errors.push(`${concept.id}: concept cannot reference itself`);
    }
  }

  const visiting = new Set<string>();
  const visited = new Set<string>();

  function visit(id: string, path: string[]) {
    if (visiting.has(id)) {
      errors.push(`Grammar prerequisite cycle: ${[...path, id].join(" -> ")}`);
      return;
    }
    if (visited.has(id)) return;
    visiting.add(id);
    const concept = byId.get(id);
    for (const prerequisite of concept?.prerequisites ?? []) visit(prerequisite, [...path, id]);
    visiting.delete(id);
    visited.add(id);
  }

  for (const concept of concepts) visit(concept.id, []);

  return [...new Set(errors)];
}

export function assertValidGrammarCurriculum(
  concepts: GrammarCurriculumConcept[] = grammarCurriculum,
) {
  const errors = validateGrammarCurriculum(concepts);
  if (errors.length > 0) {
    throw new Error(`Invalid grammar curriculum:\n- ${errors.join("\n- ")}`);
  }
}
