import type { GrammarCurriculumConcept } from "./curriculum";

export const englishGrammarCurriculum: GrammarCurriculumConcept[] = [
  { id:"en.sentence.basic-order", slug:"en-basic-word-order", title:"Basic statement word order", shortDescription:"Build neutral subject–verb–object clauses and place common complements naturally.", category:"SENTENCE_STRUCTURE", introducedAt:"A1", expectedBy:"A1", order:10, examples:["I read books.","She works in London."] },
  { id:"en.sentence.questions-be", slug:"en-questions-with-be", title:"Questions with be", shortDescription:"Invert be and the subject in yes/no and wh- questions.", category:"SENTENCE_STRUCTURE", introducedAt:"A1", expectedBy:"A1", order:20, prerequisites:["en.sentence.basic-order"], examples:["Are you ready?","Where is she?"] },
  { id:"en.sentence.do-support", slug:"en-do-support", title:"Do-support in questions and negatives", shortDescription:"Use do/does/did for questions and negatives with lexical verbs.", category:"SENTENCE_STRUCTURE", introducedAt:"A1", expectedBy:"A2", reinforcedAt:["B1"], order:30, prerequisites:["en.sentence.basic-order"], examples:["Do you work here?","She doesn't drive."] },
  { id:"en.negation.basic", slug:"en-basic-negation", title:"Basic negation", shortDescription:"Form negatives with be, auxiliaries and do-support.", category:"NEGATION", introducedAt:"A1", expectedBy:"A1", order:40, prerequisites:["en.sentence.basic-order"], examples:["I'm not tired.","He doesn't know."] },
  { id:"en.sentence.imperatives", slug:"en-imperatives", title:"Imperatives", shortDescription:"Use base-form imperatives for instructions, requests and warnings.", category:"VERBS", introducedAt:"A1", expectedBy:"A1", order:50, examples:["Open the window.","Don't touch that."] },

  { id:"en.article.a-an-the", slug:"en-a-an-the", title:"a/an and the", shortDescription:"Choose indefinite and definite articles according to reference and sound.", category:"ARTICLES", introducedAt:"A1", expectedBy:"A2", reinforcedAt:["B1"], order:100, examples:["a book","an hour","the book on the table"] },
  { id:"en.article.zero", slug:"en-zero-article", title:"Zero article", shortDescription:"Omit articles with many plural, uncountable and institutional nouns.", category:"ARTICLES", introducedAt:"A2", expectedBy:"B1", order:110, prerequisites:["en.article.a-an-the"], examples:["I like music.","Children need sleep."] },
  { id:"en.noun.countability", slug:"en-countable-uncountable", title:"Countable and uncountable nouns", shortDescription:"Distinguish countable and mass nouns for determiners, plural forms and quantity expressions.", category:"NOUNS", introducedAt:"A1", expectedBy:"A2", reinforcedAt:["B1"], order:120, examples:["two ideas","some advice","much information"] },
  { id:"en.noun.plurals", slug:"en-noun-plurals", title:"Regular and irregular plurals", shortDescription:"Form regular plurals and common irregular plural patterns.", category:"NOUNS", introducedAt:"A1", expectedBy:"A2", order:130, examples:["books","cities","children","people"] },
  { id:"en.determiner.quantifiers", slug:"en-quantifiers", title:"Quantifiers", shortDescription:"Use some, any, much, many, few, little, enough and related quantifiers.", category:"ARTICLES", introducedAt:"A2", expectedBy:"B1", prerequisites:["en.noun.countability"], order:140, examples:["some water","many people","a little time"] },

  { id:"en.pronoun.subject-object", slug:"en-subject-object-pronouns", title:"Subject and object pronouns", shortDescription:"Use subject and object pronoun forms in their normal clause positions.", category:"PRONOUNS", introducedAt:"A1", expectedBy:"A1", order:200, examples:["She knows me.","I called them."] },
  { id:"en.pronoun.possessive", slug:"en-possessives", title:"Possessives", shortDescription:"Use possessive determiners, pronouns and apostrophe-s possession.", category:"PRONOUNS", introducedAt:"A1", expectedBy:"A2", order:210, examples:["my book","This one is mine.","Sara's phone"] },
  { id:"en.pronoun.reflexive", slug:"en-reflexive-pronouns", title:"Reflexive pronouns", shortDescription:"Use myself, yourself and related forms for reflexive and emphatic meaning.", category:"PRONOUNS", introducedAt:"A2", expectedBy:"B1", order:220, prerequisites:["en.pronoun.subject-object"], examples:["She taught herself.","I did it myself."] },
  { id:"en.pronoun.relative-basic", slug:"en-relative-pronouns", title:"Relative clauses: who, which, that", shortDescription:"Form defining relative clauses with common relative pronouns.", category:"RELATIVE_CLAUSES", introducedAt:"A2", expectedBy:"B1", order:230, examples:["The person who called…","The book that I bought…"] },
  { id:"en.pronoun.relative-advanced", slug:"en-advanced-relative-clauses", title:"Advanced relative clauses", shortDescription:"Use non-defining clauses, whose, whom and preposition placement appropriately.", category:"RELATIVE_CLAUSES", introducedAt:"B2", expectedBy:"C1", prerequisites:["en.pronoun.relative-basic"], order:240, examples:["My brother, who lives abroad, …","The person to whom I wrote…"] },

  { id:"en.tense.present-simple", slug:"en-present-simple", title:"Present simple", shortDescription:"Use the present simple for routines, facts and stable situations.", category:"TENSES", introducedAt:"A1", expectedBy:"A1", order:300, examples:["I work here.","She usually walks."] },
  { id:"en.tense.present-continuous", slug:"en-present-continuous", title:"Present continuous", shortDescription:"Use be + -ing for ongoing, temporary and arranged situations.", category:"TENSES", introducedAt:"A1", expectedBy:"A2", order:310, prerequisites:["en.tense.present-simple"], examples:["I'm working now.","We're meeting tomorrow."] },
  { id:"en.tense.present-contrast", slug:"en-present-simple-vs-continuous", title:"Present simple vs present continuous", shortDescription:"Choose between habitual/stative and ongoing/temporary meanings.", category:"TENSES", introducedAt:"A2", expectedBy:"A2", prerequisites:["en.tense.present-simple","en.tense.present-continuous"], order:320, examples:["I work from home.","I'm working from home this week."] },
  { id:"en.tense.past-simple", slug:"en-past-simple", title:"Past simple", shortDescription:"Use the past simple for completed past events and sequences.", category:"TENSES", introducedAt:"A1", expectedBy:"A2", order:330, examples:["We arrived yesterday.","She went home."] },
  { id:"en.tense.past-continuous", slug:"en-past-continuous", title:"Past continuous", shortDescription:"Use was/were + -ing for background and ongoing past activity.", category:"TENSES", introducedAt:"A2", expectedBy:"B1", prerequisites:["en.tense.past-simple"], order:340, examples:["I was cooking when she called."] },
  { id:"en.tense.present-perfect", slug:"en-present-perfect", title:"Present perfect", shortDescription:"Connect past events or states to the present with have + past participle.", category:"TENSES", introducedAt:"A2", expectedBy:"B1", reinforcedAt:["B2"], order:350, prerequisites:["en.tense.past-simple"], examples:["I've finished.","She's lived here for years."] },
  { id:"en.tense.present-perfect-continuous", slug:"en-present-perfect-continuous", title:"Present perfect continuous", shortDescription:"Emphasize duration or ongoing recent activity with have been + -ing.", category:"TENSES", introducedAt:"B1", expectedBy:"B2", prerequisites:["en.tense.present-perfect","en.tense.present-continuous"], order:360, examples:["I've been waiting for an hour."] },
  { id:"en.tense.past-perfect", slug:"en-past-perfect", title:"Past perfect", shortDescription:"Mark an event completed before another past reference point.", category:"TENSES", introducedAt:"B1", expectedBy:"B2", prerequisites:["en.tense.past-simple","en.tense.present-perfect"], order:370, examples:["She had left before I arrived."] },
  { id:"en.tense.future-forms", slug:"en-future-forms", title:"Future forms", shortDescription:"Choose will, be going to, present continuous and present simple for future meanings.", category:"TENSES", introducedAt:"A2", expectedBy:"B1", reinforcedAt:["B2"], order:380, examples:["I'll call you.","We're leaving tomorrow.","The train leaves at six."] },
  { id:"en.tense.future-perfect", slug:"en-future-perfect", title:"Future perfect and continuous", shortDescription:"Express completion or duration up to a future reference point.", category:"TENSES", introducedAt:"B2", expectedBy:"C1", prerequisites:["en.tense.future-forms","en.tense.present-perfect"], order:390, examples:["I'll have finished by Friday.","I'll have been working here for ten years."] },

  { id:"en.modal.ability", slug:"en-modals-ability", title:"Ability and possibility modals", shortDescription:"Use can, could and be able to for ability and possibility.", category:"VERBS", introducedAt:"A1", expectedBy:"A2", order:400, examples:["I can swim.","We might be able to help."] },
  { id:"en.modal.obligation", slug:"en-modals-obligation", title:"Obligation and advice modals", shortDescription:"Use must, have to, should and related forms for obligation and advice.", category:"VERBS", introducedAt:"A2", expectedBy:"B1", order:410, examples:["You must stop.","You should rest."] },
  { id:"en.modal.deduction", slug:"en-modals-deduction", title:"Modals of deduction", shortDescription:"Use must, might, may, could and can't for degrees of certainty.", category:"VERBS", introducedAt:"B1", expectedBy:"B2", order:420, examples:["She must be home.","He can't have known."] },
  { id:"en.modal.perfect", slug:"en-perfect-modals", title:"Perfect modals", shortDescription:"Use modal + have + past participle for past possibility, deduction, regret and criticism.", category:"VERBS", introducedAt:"B2", expectedBy:"C1", prerequisites:["en.modal.deduction"], order:430, examples:["You should have called.","They might have missed it."] },

  { id:"en.adjective.order", slug:"en-adjective-order", title:"Adjective position and order", shortDescription:"Place adjectives before nouns or after linking verbs and order multiple adjectives naturally.", category:"ADJECTIVES", introducedAt:"A1", expectedBy:"B1", order:500, examples:["a beautiful old house","The room looks bright."] },
  { id:"en.adverb.position", slug:"en-adverb-position", title:"Adverb position", shortDescription:"Place frequency, manner, degree and sentence adverbs naturally.", category:"ADVERBS_PARTICLES", introducedAt:"A2", expectedBy:"B1", order:510, examples:["She often works late.","He spoke quietly."] },
  { id:"en.comparison.basic", slug:"en-comparatives-superlatives", title:"Comparatives and superlatives", shortDescription:"Form and use comparative and superlative adjectives and adverbs.", category:"COMPARISON", introducedAt:"A1", expectedBy:"A2", order:520, examples:["bigger than","more useful","the best"] },
  { id:"en.comparison.advanced", slug:"en-advanced-comparison", title:"Advanced comparison", shortDescription:"Use structures such as as…as, the more…the more, far/much and comparative clauses.", category:"COMPARISON", introducedAt:"B2", expectedBy:"C1", prerequisites:["en.comparison.basic"], order:530, examples:["far more effective","The sooner, the better."] },

  { id:"en.preposition.time-place", slug:"en-prepositions-time-place", title:"Prepositions of time and place", shortDescription:"Use common prepositions such as at, on, in, to and from for time and place.", category:"PREPOSITIONS", introducedAt:"A1", expectedBy:"A2", order:600, examples:["at six","on Monday","in London"] },
  { id:"en.preposition.verb-patterns", slug:"en-verb-preposition-patterns", title:"Verb and adjective preposition patterns", shortDescription:"Learn lexical patterns such as depend on, interested in and apologize for.", category:"PREPOSITIONS", introducedAt:"B1", expectedBy:"B2", reinforcedAt:["C1"], order:610, examples:["depend on","interested in","apologize for"] },
  { id:"en.particle.phrasal-verbs", slug:"en-phrasal-verbs", title:"Phrasal verbs and particles", shortDescription:"Understand particle meaning and separability in common phrasal verbs.", category:"ADVERBS_PARTICLES", introducedAt:"A2", expectedBy:"B2", reinforcedAt:["C1"], order:620, examples:["turn it off","look after someone","run into a friend"] },

  { id:"en.infinitive.gerund", slug:"en-gerunds-infinitives", title:"Gerunds and infinitives", shortDescription:"Choose -ing forms or to-infinitives after common verbs, adjectives and expressions.", category:"INFINITIVE_CONSTRUCTIONS", introducedAt:"A2", expectedBy:"B2", reinforcedAt:["C1"], order:700, examples:["enjoy reading","want to leave","good at explaining"] },
  { id:"en.infinitive.bare", slug:"en-bare-infinitive", title:"Bare infinitive patterns", shortDescription:"Use the infinitive without to after modals and selected causative/perception patterns.", category:"INFINITIVE_CONSTRUCTIONS", introducedAt:"B1", expectedBy:"B2", order:710, examples:["must go","let him speak","I saw her leave."] },

  { id:"en.conditional.zero-first", slug:"en-zero-first-conditionals", title:"Zero and first conditionals", shortDescription:"Express general consequences and realistic future conditions.", category:"CONJUNCTIONS", introducedAt:"A2", expectedBy:"B1", order:800, examples:["If you heat ice, it melts.","If it rains, we'll stay home."] },
  { id:"en.conditional.second", slug:"en-second-conditional", title:"Second conditional", shortDescription:"Express hypothetical present or future situations with past form + would.", category:"CONJUNCTIONS", introducedAt:"B1", expectedBy:"B1", prerequisites:["en.conditional.zero-first"], order:810, examples:["If I had more time, I'd travel."] },
  { id:"en.conditional.third-mixed", slug:"en-third-mixed-conditionals", title:"Third and mixed conditionals", shortDescription:"Express unreal past conditions and mixed-time consequences.", category:"CONJUNCTIONS", introducedAt:"B2", expectedBy:"C1", prerequisites:["en.conditional.second","en.tense.past-perfect"], order:820, examples:["If I'd known, I would have called.","If I'd studied medicine, I'd be a doctor now."] },

  { id:"en.passive.basic", slug:"en-passive-voice", title:"Passive voice", shortDescription:"Form be + past participle and choose passive when the actor is unknown, obvious or backgrounded.", category:"PASSIVE", introducedAt:"B1", expectedBy:"B1", order:900, examples:["The bridge was built in 1990.","It is used worldwide."] },
  { id:"en.passive.advanced", slug:"en-advanced-passives", title:"Advanced passive structures", shortDescription:"Use reporting passives, get-passives and passive infinitive/gerund forms.", category:"PASSIVE", introducedAt:"B2", expectedBy:"C1", prerequisites:["en.passive.basic"], order:910, examples:["He is believed to be abroad.","She got promoted."] },

  { id:"en.reported.basic", slug:"en-reported-speech", title:"Reported speech", shortDescription:"Report statements and questions with appropriate pronoun, time and tense choices.", category:"SENTENCE_STRUCTURE", introducedAt:"B1", expectedBy:"B2", order:1000, examples:["She said that she was tired.","He asked where I lived."] },
  { id:"en.reported.advanced", slug:"en-reporting-verbs", title:"Reporting verbs and patterns", shortDescription:"Use reporting verbs with that-clauses, infinitives and gerunds.", category:"VERBS", introducedAt:"B2", expectedBy:"C1", prerequisites:["en.reported.basic","en.infinitive.gerund"], order:1010, examples:["She advised me to wait.","He denied taking it."] },

  { id:"en.clause.subordination", slug:"en-subordinate-clauses", title:"Subordinate clauses", shortDescription:"Link ideas with because, although, while, unless, whereas and related subordinators.", category:"CONJUNCTIONS", introducedAt:"A2", expectedBy:"B1", order:1100, examples:["Although it was late, we stayed.","I'll call unless I'm busy."] },
  { id:"en.clause.participle", slug:"en-participle-clauses", title:"Participle clauses", shortDescription:"Reduce clauses with present or past participles where reference is clear.", category:"SENTENCE_STRUCTURE", introducedAt:"C1", expectedBy:"C1", prerequisites:["en.clause.subordination"], order:1110, examples:["Having finished the work, she left.","Built in 1900, the house…"] },
  { id:"en.clause.cleft", slug:"en-cleft-sentences", title:"Cleft and focus structures", shortDescription:"Use it-clefts, wh-clefts and fronting to manage focus.", category:"SENTENCE_STRUCTURE", introducedAt:"B2", expectedBy:"C1", order:1120, examples:["It was John who called.","What I need is a break."] },
  { id:"en.clause.inversion", slug:"en-inversion", title:"Inversion for emphasis and style", shortDescription:"Use negative and conditional inversion in formal or emphatic contexts.", category:"SENTENCE_STRUCTURE", introducedAt:"C1", expectedBy:"C2", order:1130, examples:["Never have I seen that.","Had I known, I would have stayed."] },
  { id:"en.clause.ellipsis", slug:"en-ellipsis-substitution", title:"Ellipsis and substitution", shortDescription:"Avoid repetition with ellipsis, do so, one/ones, so/not and related devices.", category:"SENTENCE_STRUCTURE", introducedAt:"C1", expectedBy:"C2", order:1140, examples:["I can play the guitar, and she can too.","I think so."] },

  { id:"en.wordformation.affixes", slug:"en-word-formation", title:"Word formation", shortDescription:"Build and interpret words with common prefixes, suffixes and conversion.", category:"WORD_FORMATION", introducedAt:"B1", expectedBy:"C1", reinforcedAt:["C2"], order:1200, examples:["happy → unhappy → happiness","email (noun/verb)"] },
  { id:"en.discourse.linkers", slug:"en-discourse-linkers", title:"Discourse linkers", shortDescription:"Organize arguments and narratives with contrast, cause, result and concession linkers.", category:"CONJUNCTIONS", introducedAt:"B2", expectedBy:"C1", reinforcedAt:["C2"], order:1210, examples:["however","therefore","nevertheless","on the other hand"] },
  { id:"en.discourse.hedging", slug:"en-hedging-stance", title:"Hedging and stance", shortDescription:"Control certainty, politeness and academic stance with modal and lexical hedges.", category:"ADVERBS_PARTICLES", introducedAt:"C1", expectedBy:"C2", order:1220, examples:["It appears that…","This may suggest…","arguably"] },
  { id:"en.style.register", slug:"en-register-variation", title:"Register and style", shortDescription:"Choose grammatical and lexical forms appropriate to formal, neutral and informal English.", category:"SENTENCE_STRUCTURE", introducedAt:"C1", expectedBy:"C2", order:1230, examples:["Could you possibly…?","Can you…?","gonna (informal speech)"] },
  { id:"en.style.nominalization", slug:"en-nominalization", title:"Nominalization", shortDescription:"Use noun-based structures to create dense formal and academic prose without obscuring meaning.", category:"WORD_FORMATION", introducedAt:"C1", expectedBy:"C2", prerequisites:["en.wordformation.affixes"], order:1240, examples:["The implementation of the policy…"] },
  { id:"en.discourse.information-structure", slug:"en-advanced-information-structure", title:"Advanced information structure", shortDescription:"Control theme, rheme, end focus, marked fronting and reference across complex spoken and written discourse.", category:"SENTENCE_STRUCTURE", introducedAt:"C2", expectedBy:"C2", prerequisites:["en.clause.cleft","en.clause.inversion","en.discourse.linkers"], order:1250, examples:["What the evidence does show, however, is a gradual shift.","More significant still is the change in how the issue is framed."] },
];

export function assertValidEnglishGrammarCurriculum() {
  const ids = new Set(englishGrammarCurriculum.map((item) => item.id));
  const slugs = new Set(englishGrammarCurriculum.map((item) => item.slug));
  if (ids.size !== englishGrammarCurriculum.length) {
    throw new Error("Duplicate English grammar concept ID.");
  }
  if (slugs.size !== englishGrammarCurriculum.length) {
    throw new Error("Duplicate English grammar concept slug.");
  }
  for (const concept of englishGrammarCurriculum) {
    if (!concept.id.startsWith("en.")) {
      throw new Error("English grammar IDs must start with en.: " + concept.id);
    }
    for (const prerequisite of concept.prerequisites ?? []) {
      if (!ids.has(prerequisite)) {
        throw new Error("Unknown English grammar prerequisite: " + prerequisite);
      }
    }
    for (const relation of concept.related ?? []) {
      if (!ids.has(relation.targetId)) {
        throw new Error("Unknown English grammar relation: " + relation.targetId);
      }
    }
  }
}
