import type { GrammarCurriculumConcept } from "./curriculum";

export const frenchGrammarCurriculum: GrammarCurriculumConcept[] = [
  { id:"fr.article.definite", slug:"fr-definite-articles", title:"Definite articles", shortDescription:"Use le, la, l’ and les with nouns according to gender, number and sound.", category:"ARTICLES", introducedAt:"A1", expectedBy:"A1", reinforcedAt:["A2"], order:10, examples:["le livre","la maison","l’école","les enfants"] },
  { id:"fr.article.indefinite", slug:"fr-indefinite-articles", title:"Indefinite articles", shortDescription:"Use un, une and des for indefinite noun phrases.", category:"ARTICLES", introducedAt:"A1", expectedBy:"A1", order:20, prerequisites:["fr.article.definite"], examples:["un café","une idée","des amis"] },
  { id:"fr.noun.gender-number", slug:"fr-noun-gender-number", title:"Noun gender and number", shortDescription:"Track masculine/feminine gender and form common plurals.", category:"NOUNS", introducedAt:"A1", expectedBy:"A2", reinforcedAt:["B1"], order:30, examples:["un ami / une amie","un journal / des journaux"] },
  { id:"fr.article.partitive", slug:"fr-partitive-articles", title:"Partitive articles", shortDescription:"Use du, de la, de l’ and des for unspecified quantities.", category:"ARTICLES", introducedAt:"A1", expectedBy:"A2", reinforcedAt:["B1"], order:40, prerequisites:["fr.article.definite"], examples:["du pain","de la musique","de l’eau"] },
  { id:"fr.article.negation-de", slug:"fr-articles-after-negation", title:"Articles after negation", shortDescription:"Use de/d’ after many negative expressions instead of an indefinite or partitive article.", category:"ARTICLES", introducedAt:"A2", expectedBy:"A2", order:50, prerequisites:["fr.article.indefinite","fr.article.partitive"], examples:["Je n’ai pas de voiture.","Il ne boit pas d’alcool."] },

  { id:"fr.verb.present-er", slug:"fr-present-er-verbs", title:"Present tense: -er verbs", shortDescription:"Conjugate regular -er verbs in the present tense.", category:"VERBS", introducedAt:"A1", expectedBy:"A1", order:100, examples:["je parle","nous parlons","ils regardent"] },
  { id:"fr.verb.avoir-etre", slug:"fr-avoir-etre", title:"avoir and être", shortDescription:"Use the irregular present forms of avoir and être.", category:"VERBS", introducedAt:"A1", expectedBy:"A1", order:110, examples:["J’ai faim.","Nous sommes prêts."] },
  { id:"fr.verb.irregular-present", slug:"fr-irregular-present", title:"Common irregular present verbs", shortDescription:"Use high-frequency irregular verbs such as aller, faire, venir and prendre.", category:"VERBS", introducedAt:"A1", expectedBy:"A2", reinforcedAt:["B1"], order:120, prerequisites:["fr.verb.avoir-etre"], examples:["Je vais au travail.","Elle fait du sport."] },
  { id:"fr.verb.pronominal", slug:"fr-pronominal-verbs", title:"Pronominal verbs", shortDescription:"Use reflexive/pronominal verbs with matching clitic pronouns.", category:"VERBS", introducedAt:"A1", expectedBy:"A2", reinforcedAt:["B1"], order:130, examples:["Je me lève.","Nous nous souvenons."] },
  { id:"fr.verb.imperative", slug:"fr-imperative", title:"Imperative", shortDescription:"Form commands and requests with tu, nous and vous forms.", category:"VERBS", introducedAt:"A2", expectedBy:"A2", order:140, prerequisites:["fr.verb.present-er"], examples:["Parle plus lentement.","Allons-y !","Attendez ici."] },

  { id:"fr.sentence.basic-order", slug:"fr-basic-word-order", title:"Basic statement word order", shortDescription:"Build neutral French clauses with subject, verb and complements in natural order.", category:"SENTENCE_STRUCTURE", introducedAt:"A1", expectedBy:"A1", order:200, examples:["Marie lit un livre.","Nous travaillons demain."] },
  { id:"fr.sentence.questions", slug:"fr-questions", title:"Questions", shortDescription:"Form questions with intonation, est-ce que and inversion where appropriate.", category:"SENTENCE_STRUCTURE", introducedAt:"A1", expectedBy:"A2", reinforcedAt:["B1"], order:210, prerequisites:["fr.sentence.basic-order"], examples:["Tu viens ?","Est-ce que tu viens ?","Venez-vous ?"] },
  { id:"fr.negation.ne-pas", slug:"fr-ne-pas-negation", title:"Negation with ne…pas", shortDescription:"Place ne/n’ and pas around the finite verb.", category:"NEGATION", introducedAt:"A1", expectedBy:"A1", reinforcedAt:["A2"], order:220, prerequisites:["fr.sentence.basic-order"], examples:["Je ne comprends pas.","Il n’aime pas le café."] },
  { id:"fr.negation.advanced", slug:"fr-advanced-negation", title:"Other negative expressions", shortDescription:"Use ne…jamais, ne…plus, ne…rien, ne…personne and related patterns.", category:"NEGATION", introducedAt:"A2", expectedBy:"B1", order:230, prerequisites:["fr.negation.ne-pas"], examples:["Je ne vois rien.","Elle ne vient jamais."] },

  { id:"fr.pronoun.subject", slug:"fr-subject-pronouns", title:"Subject pronouns", shortDescription:"Use je, tu, il/elle/on, nous, vous and ils/elles.", category:"PRONOUNS", introducedAt:"A1", expectedBy:"A1", order:300, examples:["Je travaille.","On commence ?","Elles arrivent."] },
  { id:"fr.pronoun.direct-object", slug:"fr-direct-object-pronouns", title:"Direct object pronouns", shortDescription:"Use me, te, le, la, nous, vous and les before the verb.", category:"PRONOUNS", introducedAt:"A2", expectedBy:"B1", order:310, prerequisites:["fr.pronoun.subject"], examples:["Je le connais.","Elle les invite."] },
  { id:"fr.pronoun.indirect-object", slug:"fr-indirect-object-pronouns", title:"Indirect object pronouns", shortDescription:"Use lui and leur for many à + person complements.", category:"PRONOUNS", introducedAt:"A2", expectedBy:"B1", order:320, prerequisites:["fr.pronoun.direct-object"], examples:["Je lui parle.","Nous leur écrivons."] },
  { id:"fr.pronoun.y-en", slug:"fr-y-en-pronouns", title:"y and en", shortDescription:"Replace common à/location and de/quantity complements with y and en.", category:"PRONOUNS", introducedAt:"B1", expectedBy:"B1", reinforcedAt:["B2"], order:330, prerequisites:["fr.pronoun.direct-object"], examples:["J’y vais.","J’en veux deux."] },
  { id:"fr.pronoun.order", slug:"fr-object-pronoun-order", title:"Object pronoun order", shortDescription:"Order multiple object pronouns correctly before verbs and infinitives.", category:"PRONOUNS", introducedAt:"B1", expectedBy:"B2", order:340, prerequisites:["fr.pronoun.indirect-object","fr.pronoun.y-en"], examples:["Je le lui donne.","Il va m’en parler."] },
  { id:"fr.pronoun.relative-basic", slug:"fr-relative-qui-que", title:"Relative pronouns qui and que", shortDescription:"Link clauses with qui as subject and que as object.", category:"RELATIVE_CLAUSES", introducedAt:"A2", expectedBy:"B1", order:350, examples:["La femme qui parle…","Le livre que je lis…"] },
  { id:"fr.pronoun.relative-advanced", slug:"fr-relative-dont-ou-lequel", title:"Relative pronouns dont, où and lequel", shortDescription:"Use more advanced relative pronouns for de-complements, place/time and prepositional relations.", category:"RELATIVE_CLAUSES", introducedAt:"B1", expectedBy:"B2", reinforcedAt:["C1"], order:360, prerequisites:["fr.pronoun.relative-basic"], examples:["Le film dont je parle…","La ville où je vis…"] },

  { id:"fr.adjective.agreement", slug:"fr-adjective-agreement", title:"Adjective agreement", shortDescription:"Make adjectives agree in gender and number.", category:"ADJECTIVES", introducedAt:"A1", expectedBy:"A2", reinforcedAt:["B1"], order:400, examples:["un petit café","une petite maison","des maisons blanches"] },
  { id:"fr.adjective.position", slug:"fr-adjective-position", title:"Adjective position", shortDescription:"Choose natural pre- or post-nominal adjective placement and understand meaning shifts.", category:"ADJECTIVES", introducedAt:"A2", expectedBy:"B1", order:410, prerequisites:["fr.adjective.agreement"], examples:["un grand homme","un homme grand","une voiture rouge"] },
  { id:"fr.comparison.basic", slug:"fr-comparison", title:"Comparatives and superlatives", shortDescription:"Use plus, moins, aussi and le/la/les plus or moins.", category:"COMPARISON", introducedAt:"A2", expectedBy:"A2", order:420, examples:["plus rapide que","aussi utile que","le plus intéressant"] },

  { id:"fr.preposition.a-de", slug:"fr-a-de-prepositions", title:"Core uses of à and de", shortDescription:"Use à and de in common complements, possession and fixed patterns.", category:"PREPOSITIONS", introducedAt:"A1", expectedBy:"A2", reinforcedAt:["B1"], order:500, examples:["parler à quelqu’un","venir de Paris","le livre de Marie"] },
  { id:"fr.preposition.countries", slug:"fr-countries-cities-prepositions", title:"Prepositions with places", shortDescription:"Use à, en, au, aux and de/from forms with cities and countries.", category:"PREPOSITIONS", introducedAt:"A1", expectedBy:"A2", order:510, examples:["à Paris","en France","au Canada","aux États-Unis"] },
  { id:"fr.preposition.verb-patterns", slug:"fr-verb-preposition-patterns", title:"Verb + preposition patterns", shortDescription:"Learn verbs that select à, de or another fixed preposition.", category:"PREPOSITIONS", introducedAt:"B1", expectedBy:"B2", reinforcedAt:["C1"], order:520, prerequisites:["fr.preposition.a-de"], examples:["réussir à faire","essayer de faire","compter sur quelqu’un"] },

  { id:"fr.tense.passe-compose", slug:"fr-passe-compose", title:"Passé composé", shortDescription:"Form the common completed past with avoir/être plus past participle.", category:"TENSES", introducedAt:"A2", expectedBy:"A2", reinforcedAt:["B1"], order:600, prerequisites:["fr.verb.avoir-etre"], examples:["J’ai travaillé.","Elle est arrivée."] },
  { id:"fr.tense.imparfait", slug:"fr-imparfait", title:"Imparfait", shortDescription:"Describe ongoing, habitual and background past situations.", category:"TENSES", introducedAt:"A2", expectedBy:"B1", reinforcedAt:["B2"], order:610, examples:["Quand j’étais petit, je jouais dehors."] },
  { id:"fr.tense.past-contrast", slug:"fr-passe-compose-vs-imparfait", title:"Passé composé vs imparfait", shortDescription:"Choose between completed foreground events and background/habitual past.", category:"TENSES", introducedAt:"B1", expectedBy:"B1", reinforcedAt:["B2"], order:620, prerequisites:["fr.tense.passe-compose","fr.tense.imparfait"], examples:["Il pleuvait quand je suis sorti."] },
  { id:"fr.tense.plus-que-parfait", slug:"fr-plus-que-parfait", title:"Plus-que-parfait", shortDescription:"Express an event completed before another past reference point.", category:"TENSES", introducedAt:"B1", expectedBy:"B2", order:630, prerequisites:["fr.tense.past-contrast"], examples:["J’avais déjà mangé quand il est arrivé."] },
  { id:"fr.tense.future-proche", slug:"fr-futur-proche", title:"Futur proche", shortDescription:"Use aller + infinitive for near or planned future.", category:"TENSES", introducedAt:"A1", expectedBy:"A2", order:640, prerequisites:["fr.verb.irregular-present"], examples:["Je vais partir."] },
  { id:"fr.tense.future-simple", slug:"fr-futur-simple", title:"Futur simple", shortDescription:"Form and use the simple future for predictions, plans and formal future reference.", category:"TENSES", introducedAt:"A2", expectedBy:"B1", reinforcedAt:["B2"], order:650, examples:["Je partirai demain."] },
  { id:"fr.tense.future-perfect", slug:"fr-futur-anterieur", title:"Futur antérieur", shortDescription:"Express a future event completed before another future point.", category:"TENSES", introducedAt:"B2", expectedBy:"C1", order:660, prerequisites:["fr.tense.future-simple","fr.tense.passe-compose"], examples:["Quand tu arriveras, j’aurai fini."] },

  { id:"fr.conditional.present", slug:"fr-conditionnel-present", title:"Conditionnel présent", shortDescription:"Use the present conditional for politeness, hypothetical results and reported uncertainty.", category:"SUBJUNCTIVE", introducedAt:"B1", expectedBy:"B1", reinforcedAt:["B2"], order:700, prerequisites:["fr.tense.future-simple"], examples:["Je voudrais un café.","Je partirais si je pouvais."] },
  { id:"fr.conditional.past", slug:"fr-conditionnel-passe", title:"Conditionnel passé", shortDescription:"Express unreal past results and hindsight.", category:"SUBJUNCTIVE", introducedAt:"B2", expectedBy:"C1", order:710, prerequisites:["fr.conditional.present","fr.tense.plus-que-parfait"], examples:["J’aurais accepté si j’avais su."] },
  { id:"fr.subjunctive.present", slug:"fr-subjonctif-present", title:"Subjonctif présent", shortDescription:"Use the present subjunctive after common triggers of necessity, emotion, doubt and evaluation.", category:"SUBJUNCTIVE", introducedAt:"B1", expectedBy:"B2", reinforcedAt:["C1"], order:720, examples:["Il faut que tu viennes.","Je suis content qu’elle soit là."] },
  { id:"fr.subjunctive.advanced", slug:"fr-subjonctif-advanced", title:"Advanced subjunctive use", shortDescription:"Handle relative clauses, conjunctions and nuanced mood contrasts requiring or favoring the subjunctive.", category:"SUBJUNCTIVE", introducedAt:"C1", expectedBy:"C1", reinforcedAt:["C2"], order:730, prerequisites:["fr.subjunctive.present"], examples:["Bien qu’il soit tard…","Je cherche quelqu’un qui puisse m’aider."] },

  { id:"fr.conjunction.coordination", slug:"fr-coordinating-conjunctions", title:"Coordinating conjunctions", shortDescription:"Connect clauses with et, mais, ou, donc, car and related connectors.", category:"CONJUNCTIONS", introducedAt:"A1", expectedBy:"A2", order:800, examples:["Je viens, mais je ne reste pas."] },
  { id:"fr.conjunction.subordination", slug:"fr-subordinating-conjunctions", title:"Common subordinate clauses", shortDescription:"Use parce que, quand, si, que and other frequent subordinators.", category:"CONJUNCTIONS", introducedAt:"A2", expectedBy:"B1", order:810, prerequisites:["fr.sentence.basic-order"], examples:["Je reste parce qu’il pleut.","Si tu veux, on peut partir."] },
  { id:"fr.conjunction.si-clauses", slug:"fr-si-clauses", title:"si clauses", shortDescription:"Combine si clauses with appropriate present, future, imperfect and conditional forms.", category:"CONJUNCTIONS", introducedAt:"B1", expectedBy:"B2", order:820, prerequisites:["fr.conditional.present","fr.tense.imparfait"], examples:["Si j’ai le temps, je viendrai.","Si j’avais le temps, je viendrais."] },
  { id:"fr.conjunction.discourse", slug:"fr-discourse-connectors", title:"Discourse connectors", shortDescription:"Structure arguments and narratives with connectors such as pourtant, cependant, en revanche and par conséquent.", category:"CONJUNCTIONS", introducedAt:"B2", expectedBy:"C1", reinforcedAt:["C2"], order:830, examples:["Cependant, cette solution reste coûteuse."] },

  { id:"fr.participle.agreement", slug:"fr-past-participle-agreement", title:"Past participle agreement", shortDescription:"Apply core agreement rules with être and preceding direct objects where required.", category:"VERBS", introducedAt:"B1", expectedBy:"B2", reinforcedAt:["C1"], order:900, prerequisites:["fr.tense.passe-compose","fr.pronoun.direct-object"], examples:["Elle est arrivée.","Les lettres que j’ai écrites…"] },
  { id:"fr.gerund.present-participle", slug:"fr-gerund-present-participle", title:"Gérondif and present participle", shortDescription:"Use en + present participle and the present participle for simultaneous action and modifier-like relations.", category:"INFINITIVE_CONSTRUCTIONS", introducedAt:"B1", expectedBy:"B2", order:910, examples:["Il apprend en lisant.","Les personnes vivant ici…"] },
  { id:"fr.infinitive.complements", slug:"fr-infinitive-complements", title:"Infinitive complements", shortDescription:"Choose direct infinitives or à/de + infinitive after common verbs and adjectives.", category:"INFINITIVE_CONSTRUCTIONS", introducedAt:"A2", expectedBy:"B1", reinforcedAt:["B2"], order:920, examples:["Je veux partir.","J’essaie de comprendre.","J’apprends à conduire."] },

  { id:"fr.passive.basic", slug:"fr-passive-voice", title:"Passive voice", shortDescription:"Form the passive with être + past participle and express the agent when useful.", category:"PASSIVE", introducedAt:"B1", expectedBy:"B2", order:1000, prerequisites:["fr.verb.avoir-etre"], examples:["Le projet est financé par la ville."] },
  { id:"fr.passive.alternatives", slug:"fr-passive-alternatives", title:"Passive alternatives", shortDescription:"Use on, pronominal constructions and other idiomatic alternatives to the passive.", category:"PASSIVE", introducedAt:"B2", expectedBy:"C1", order:1010, prerequisites:["fr.passive.basic","fr.verb.pronominal"], examples:["On parle français ici.","Ce produit se vend bien."] },

  { id:"fr.reported-speech.basic", slug:"fr-reported-speech", title:"Reported speech", shortDescription:"Report statements and questions with appropriate complementizers and pronoun/reference changes.", category:"SENTENCE_STRUCTURE", introducedAt:"B1", expectedBy:"B2", order:1100, examples:["Il dit qu’il vient.","Elle demande si tu es prêt."] },
  { id:"fr.reported-speech.sequence", slug:"fr-reported-speech-sequence", title:"Sequence of tenses in reported speech", shortDescription:"Adjust tense relationships when reporting from a past viewpoint.", category:"TENSES", introducedAt:"C1", expectedBy:"C1", order:1110, prerequisites:["fr.reported-speech.basic","fr.tense.past-contrast"], examples:["Il a dit qu’il viendrait le lendemain."] },

  { id:"fr.wordformation.prefix-suffix", slug:"fr-word-formation", title:"Word formation", shortDescription:"Recognize productive prefixes, suffixes and noun/adjective/verb families.", category:"WORD_FORMATION", introducedAt:"B2", expectedBy:"C1", reinforcedAt:["C2"], order:1200, examples:["possible / impossible","nation / national / nationaliser"] },
  { id:"fr.adverb.formation", slug:"fr-adverb-formation", title:"Adverb formation and placement", shortDescription:"Form many adverbs in -ment and place common adverbs naturally.", category:"ADVERBS_PARTICLES", introducedAt:"A2", expectedBy:"B1", reinforcedAt:["B2"], order:1210, examples:["rapidement","Elle a bien compris.","Il parle souvent français."] },

  { id:"fr.style.cleft", slug:"fr-cleft-sentences", title:"Cleft and focus constructions", shortDescription:"Use c’est…qui/que and related structures to focus information.", category:"SENTENCE_STRUCTURE", introducedAt:"B2", expectedBy:"C1", order:1300, examples:["C’est Marie qui a appelé.","Ce que je veux, c’est partir."] },
  { id:"fr.style.nominalization", slug:"fr-nominalization", title:"Nominalization", shortDescription:"Use noun-based structures for denser formal and academic expression.", category:"WORD_FORMATION", introducedAt:"C1", expectedBy:"C2", order:1310, prerequisites:["fr.wordformation.prefix-suffix"], examples:["La mise en œuvre du projet…"] },
  { id:"fr.style.register", slug:"fr-register-variation", title:"Register and spoken/written variation", shortDescription:"Control formal, neutral and colloquial grammatical choices without confusing them.", category:"SENTENCE_STRUCTURE", introducedAt:"C1", expectedBy:"C2", order:1320, examples:["Nous ne savons pas. / On sait pas.","Cela / ça"] },
  { id:"fr.style.literary-tenses", slug:"fr-literary-tenses", title:"Literary past tenses", shortDescription:"Recognize and interpret passé simple and related literary tense usage.", category:"TENSES", introducedAt:"C1", expectedBy:"C2", order:1330, prerequisites:["fr.tense.past-contrast"], examples:["Il entra, regarda autour de lui et repartit."] },
  { id:"fr.style.advanced-cohesion", slug:"fr-advanced-cohesion", title:"Advanced cohesion and reference", shortDescription:"Manage reference, substitution, connector choice and information flow in complex discourse.", category:"SENTENCE_STRUCTURE", introducedAt:"C2", expectedBy:"C2", order:1340, prerequisites:["fr.conjunction.discourse","fr.pronoun.relative-advanced"], examples:["Ce faisant, l’auteur nuance l’argument présenté auparavant."] },
];

export function assertValidFrenchGrammarCurriculum() {
  const ids = new Set(frenchGrammarCurriculum.map((item) => item.id));
  const slugs = new Set(frenchGrammarCurriculum.map((item) => item.slug));
  if (ids.size !== frenchGrammarCurriculum.length) throw new Error("Duplicate French grammar concept ID.");
  if (slugs.size !== frenchGrammarCurriculum.length) throw new Error("Duplicate French grammar concept slug.");
  for (const concept of frenchGrammarCurriculum) {
    if (!concept.id.startsWith("fr.")) throw new Error("French grammar IDs must start with fr.: " + concept.id);
    for (const prerequisite of concept.prerequisites ?? []) {
      if (!ids.has(prerequisite)) throw new Error("Unknown French grammar prerequisite: " + prerequisite);
    }
    for (const relation of concept.related ?? []) {
      if (!ids.has(relation.targetId)) throw new Error("Unknown French grammar relation: " + relation.targetId);
    }
  }
}
